### ISSUE TITLE
Dokumentasjonen bør henvise til oppslagtjenesten for org.nr. til postkasselevernadøren

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#102]
På dokumentasjonssiden her: http://difi.github.io/sikker-digital-post-klient-dotnet/#sendepost
Står det skrevet følgende:

"Husk atOrgnummerPostkasse er organisasjonsnummer til leverandør av postkassetjenesten. Dette er 984661185 for Posten, og 996460320 for EBoks"

Dette bør endres, slik at ikke avsendere tror de skal hardkode disse verdiene. 
Forslag til ny tekst:

"Husk at OrgnummerPostkasse er organisasjonsnummer til leverandør av postkassetjenesten. Dette er organisasjonsnummeret leveres fra oppslagstjenesten sammen med postkasseadressen og sertifikatet til innbygger"

**Comment by asjafjell** [comment]
Dette er nå fikset.
