### ISSUE TITLE
Dokumentasjonen er digipost spesfikk, tar ikke hensyn til forskjeller mellom leverandørene

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#103]
Følgende dokumentasjon er feil for digital post:

"Ved Sikkerhetsnivå.Nivå4 vil tittelen være Konfidensielt brev. Dokument.Filnavn er visningsnavn for filen i digital postkasse. Merk at filnavn trenger ikke ha filendelse. Ved nedlasting av fil vil filnavn være en kombinasjon av dato og Dokument.Filnavn."

**Comment by asjafjell** [comment]
Hva er det som er feil her?

**Comment by aberner** [comment]
noe mer informasjon her: http://begrep.difi.no/Felles/ikkeSensitivTittel

**Comment by fredrikbach** [comment]
Jeg oppdaterer dokumentasjonen ila. uken.

**Comment by fredrikbach** [comment]
Har oppdatert til å bare peke til begrep siden om IkkeSensitivTittel. Tenkte det vare enklere enn å forvalte denne forklaringen to steder.
