### ISSUE TITLE
Feilaktig dokumentasjon knyttet til mottaker sertifikater

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#104]
Hva menes med følgende tekst i dokumentasjonen?

"Legg inn mottakersertifikat i certificate store

 Mottakerens sertifikat vil være sertifikatet til Digipost eller E-Boks og brukes for å validere respons.

Hvis du skal kjøre mot Digiposts testmiljø (https://qaoffentlig.meldingsformidler.digipost.no/api/ebms), så skal du bruke Test_Digipost.cer. Høyreklikk og lagre til disk."

Dette er feil informasjon. 
Se mer informasjon her: http://begrep.difi.no/SikkerDigitalPost/utkast/sikkerhet/sertifikathandtering

- Avsendere skal stole på sertifikatene til Buypass og Commfides som utsteder sertifikater.
- Det er meldingsformidler testmiljøet skal omtales som nettopp meldingsformidler sitt testmiljø, ikke digipost.

**Comment by asjafjell** [comment]
Hei!

Her har du helt rett! Jeg har kikket på koden som gjør validering av responsen, og her gjøres validering av sertifikatet ved at vi sjekker om det er i kjeden til de rotsertifikatene du refererer til. Vi bruker aldri Digipost_Test i koden. Dette er nok noe som henger der fra tidligere og skal bare kunne fjernes.

Er det slik at samme typen validering skal gjøres for Oppslagstjeneste V4 også med de samme rotsertifikatene?

**Comment by aberner** [comment]
@asjafjell ja, oppslagstjenesten gjør samme validering.

**Comment by asjafjell** [comment]
Da skal vi få ordnet dette så raskt det lar seg gjøre.

**Comment by asjafjell** [comment]
Denne er nå løst. Oppretter bug på Oppslagstjenesten for å få fikset det samme der.
