### ISSUE TITLE
Nullref exception dersom varselEtterDager ikke settes

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#105]
Jeg forsøkte å sette opp et varsel for SMS på meldingen, hvor siste parameteret i SmsVarsel er «varselEtterDager», hvis denne ikke er satt (som er kodemessig lovlig). Så ender det opp i en nullref exception.

**Comment by asjafjell** [comment]
Fikset i v1.2.5760.21366
