### ISSUE TITLE
Problemer med å få sendt post på vegne av annen virksomhet

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#106]
jeg forsøker å få sendt post på vegne av en annen virksomhet.

Jeg har følgende:

- et sertifikat med følgende org nr: 123456789
- static string avsender = "987654321";
- static string databehandler= "123456789";
- Avsender a = new Avsender(avsender);
- Databehandler dbh = new Databehandler(databehandler, thumbprint);

Dette resulterer i følgende request:

`
<env:Body xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="soapBody">
<ns3:StandardBusinessDocument xmlns:ns3="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader" xmlns:ns5="http://www.w3.org/2000/09/xmldsig#" xmlns:ns9="http://begrep.difi.no/sdp/schema_v10">
<ns3:StandardBusinessDocumentHeader>
<ns3:HeaderVersion>1.0</ns3:HeaderVersion>
<ns3:Sender>
 <ns3:Identifier Authority="iso6523-actorid-upis">9908:987654321</ns3:Identifier>
<ns9:avsender>
<ns9:organisasjon authority="iso6523-actorid-upis">9908:987654321</ns9:organisasjon>
`

og følgende feilmelding tilbake:

- «Organisation number from SBD Signing certificate should match SBDH sender».

Forventet at det skulle gitt følgende request:

`<env:Body xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="soapBody">
<ns3:StandardBusinessDocument xmlns:ns3="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader" xmlns:ns5="http://www.w3.org/2000/09/xmldsig#" xmlns:ns9="http://begrep.difi.no/sdp/schema_v10">
<ns3:StandardBusinessDocumentHeader>
<ns3:HeaderVersion>1.0</ns3:HeaderVersion>
<ns3:Sender>
<ns3:Identifier Authority="iso6523-actorid-upis">9908:123456789</ns3:Identifier>
  <ns9:avsender>
<ns9:organisasjon authority="iso6523-actorid-upis">9908:987654321</ns9:organisasjon>
`

**Comment by aberner** [comment]
@asjafjell kan du se på denne. Det stopper utviklingen for en viktig avsender.

**Comment by aberner** [comment]
Feilen er bekreftet og vil bli utbedret.

**Comment by asjafjell** [comment]
Fiks er nå lagt ut som beta-versjon v1.2.5758.22792. Den finner du med å velge _Include Prerelease_ i Nuget pakkehåndterer. Gi lyd om det går fint nå, så får vi lukket denne.

**Comment by aberner** [comment]
@asjafjell takk. Denne fiksen ser ut til å løse problemet.

**Comment by asjafjell** [comment]
Denne er nå prodsatt som versjon v1.2.5759.22220. Saken lukkes.
