### ISSUE TITLE
Dokumentasjonsnettstedet refererer feil nuget pakke

### ISSUE THREAD

**Issue by austrheim** [difi/sikker-digital-post-klient-dotnet#108]
Øverst på http://difi.github.io/sikker-digital-post-klient-dotnet/ er det en lenke til nuget pakken (nuget.org).

Denne linker til:

https://www.nuget.org/packages/sikker-digital-post-net-klient/

Korrekt lenke er:

https://www.nuget.org/packages/difi-sikker-digital-post-klient/

**Comment by asjafjell** [comment]
Godt observert, @austrheim  Dette er nå fikset.
