### ISSUE TITLE
Tidspunkt på kvitteringene blir hentet fra ebms header og ikke fra forretningskvitteringen

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#112]
Feil i https://github.com/difi/sikker-digital-post-klient-dotnet/blob/master/Difi.SikkerDigitalPost.Klient.Domene/Entiteter/Kvitteringer/Kvittering.cs

Den henter tidspunkt fra EBMS header og ikke fra forretningskvitteringen som er det Avsendere er interessert i.

har gjort følgende test:

- Sendte inn en mld. kl 15:13.
- Kl 15:26 sendte jeg avgårde en kvitteringsforespørsel
- Fikk tilbake en leveringsbekreftelse med Tidspunkt 15:26

Etter det så jeg i meldingsobjektet, og der står det som følger (i forretningskvitteringen):

`<ns9:tidspunkt>2015-10-12T15:13:59.642+02:00</ns9:tidspunkt>
<ns9:levering/>
</ns9:kvittering>
</ns3:StandardBusinessDocument>`

Altså, der står det tidspunktet som jeg egentlig ønsker og forventer.
Men litt lengre opp i meldingen står følgende ( EBMS header):

`<ns6:MessageInfo>
<ns6:Timestamp>2015-10-12T15:26:19.747+02:00</ns6:Timestamp>
<ns6:MessageId>b16113e3-8ff7-4ceb-b795-02e7ac2bedfb</ns6:MessageId>`

Som da er tidspunktet jeg faktisk får tilbake fra klientbiblioteket.

https://github.com/difi/sikker-digital-post-klient-dotnet/blob/master/Difi.SikkerDigitalPost.Klient.Domene/Entiteter/Kvitteringer/Kvittering.cs

linje 41: «Tidspunkt = Convert.ToDateTime(DocumentNode("//ns6:Timestamp").InnerText);»

bruker feil tidspunkt.

Ser også i samme fil på linje  12-15 står det: 
`«
/// <summary>
/// Tidspunktet da kvitteringen ble sendt.
/// </summary>
public DateTime Tidspunkt { get; protected set; }»`

Dette betyr nok at det er en misforståelse her. For tidspunktet som er interessant for Avsender er ikke når kvitteringen ble sendt fra Avsender men når kvitteringen ble skapt hos postkasse eller utskriftsleverandør.

Oppsummert:

- Koden benytter seg ikke av «Tidspunkt» i melding, men «Timestamp».

**Comment by asjafjell** [comment]
Sitter for øyeblikket med #119, da den ble vurdert som mer sentral for funksjonaliteten av bibilioteket. Vi kan gjerne hoppe på denne etterpå om det er ønskelig. 

Takk for en fyldig og god beskrivelse, @aberner. Er det da ønskelig at vi endrer `Tidspunkt` eller vil du ha flere tidspunkt tilgjengelig?

**Comment by kristianenge** [comment]
Kan testes i branch: [b_foretningskvitteringTidspunkt](https://github.com/difi/sikker-digital-post-klient-dotnet/tree/b_foretningskvitteringTidspunkt)

**Comment by asjafjell** [comment]
Denne er fikset i [1.4.5806.28577](https://github.com/difi/sikker-digital-post-klient-dotnet/releases/tag/v1.4.5806.28577)
