### ISSUE TITLE
Ønsker mulighet for å stoppe requester til feil miljø

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#113]
ref. https://github.com/difi/sikker-digital-post-java-klient/issues/34

Tilsvarende funksjonalitet i .net biblioteket.

**Comment by asjafjell** [comment]
Denne oppgaven er i tråd med det vi har jobbet med for validering av respons, som skal være ute i løpet av noen dager.

**Comment by asjafjell** [comment]
Denne er fikset i [v1.9.0.25241](https://github.com/difi/sikker-digital-post-klient-dotnet/releases/tag/v1.9.0.25241).
