### ISSUE TITLE
URL til meldingsformidler bør inneholde org.nummer til avsender

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#114]
ref. https://github.com/difi/sikker-digital-post-java-klient/issues/35

Ønsker tilsvarende funksjonalitet i .net biblioteket

**Comment by asjafjell** [comment]
Denne er nå fikset i [v1.10.0.25393](https://github.com/difi/sikker-digital-post-klient-dotnet/releases/tag/v1.10.0.25393).
