### ISSUE TITLE
KonversasjonsId er ReadOnly - vi ønsker å sette denne selv

### ISSUE THREAD

**Issue by aklefdal** [difi/sikker-digital-post-klient-dotnet#115]
I klassen Forsendelse er KonversasjonsId definert som en public readonly instansvariabel, som settes til en ny guid ved konstruksjon. Vi ønsker å ha kontroll på dette feltet selv, og helt spesifikt ønsker vi å sette dette feltet til den konversasjonsid'en som vi allerede får fra systemet som produserer brevene.

Bakgrunnen for dette er at vi jobber basert på en kø. Dersom forsendelsen feiler, fx på grunn av nettverksfeil eller lignende, så avslutter vi forsøket, og prøver igjen, for eksempel 5 minutter senere. Vi står da i fare for å få dobbel forsendelse.

**Comment by asjafjell** [comment]
Hei, @aklefdal!

Vi har kikket litt på dette og det gir mening. Om dere ønsker å gjenskape en identisk melding så bør dette være mulig. 

Vi skal ta tak i dette så snart vi kan!

**Comment by asjafjell** [comment]
Hei! Dette er nå løst i 1.2.5777.23323-beta. Kan du laste ned denne versjonen og se om det er som ønsket, @aklefdal?

**Comment by aklefdal** [comment]
Vi har nå lastet ned og installert pakken. Så langt ser det bra ut. I morgen skal vi gjennom grundigere testing i testmiljøet.

**Comment by asjafjell** [comment]
Fint å høre. Da sier vi denne er lukket for nå.
