### ISSUE TITLE
Kall til SDP feiler ved CurrentUICulture = "nb-NO"

### ISSUE THREAD

**Issue by aklefdal** [difi/sikker-digital-post-klient-dotnet#117]
Dersom kall til for eksempel HentKvittering gjøres når CurrentUICulture er satt til "nb-NO", så feiler det før selve kallet blir sendt avgårde til Difi:
 
	  
	System.AggregateException was unhandled by user code
	  HResult=-2146233088
	  Message=Det oppsto én eller flere feil.
	  Source=mscorlib
	  StackTrace:
		   ved System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
		   ved System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
		   ved System.Threading.Tasks.Task`1.get_Result()
		   ved Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.HentKvittering(Kvitteringsforespørsel kvitteringsforespørsel)
		   ved UDI.ULFESB.DigitalPost.Core.Difi.DifiSikkerDigitalPost.HentKvittering() i C:\s\V09\UIP\DigitalPost\Core\Difi\DifiSikkerDigitalPost.cs:linje 101
		   ved UDI.ULFESB.DigitalPost.IntegrationTests.Forbindelse mot Difi.Vi har forbindelse med Difi digital postkasse() i C:\s\V09\UIP\DigitalPost\IntegrationTests\ForbindelseMotDifi.fs:linje 29
	  InnerException: 
		   HResult=-2146233088
		   Message= Validering av Xml feilet: Kvitteringsforespørsel validerer ikke mot xsd:	Validation error: Det er en feil hvis det finnes et medlem av attributtet som bruker en typedefinisjon med typen xs:ID eller avledet fra xs:ID og et annet attributt med typen xs:ID tilsvarer et attributtjokertegn.

		   Source=Difi.SikkerDigitalPost.Klient
		   StackTrace:
				ved Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.ValiderKvitteringsEnvelope(KvitteringsforespørselEnvelope kvitteringsenvelope)
				ved Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.<HentKvitteringOgBekreftForrigeAsync>d__b.MoveNext()
		   InnerException: 

Dette er kun observert på Windows 7, og jeg har ikke klart å reprodusere feilen på Windows 8.1.

**Comment by asjafjell** [comment]
Hei, @aklefdal. Er dette fortsatt et problem på Windows 7?

**Comment by asjafjell** [comment]
Lukker denne pga. inaktivitet. Det er bare å åpne denne om du klarer å gjenskape den, @aklefdal.
