### ISSUE TITLE
Behov for å vite størrelse på lagret Dokumentpakke

### ISSUE THREAD

**Issue by austrheim** [difi/sikker-digital-post-klient-dotnet#118]
Vi har behov for å vite størrelsen på Dokumentpakken som lagres ref: [Prisen på en forsendelse regnes ut i fra størrelsen på Dokumentpakkens innhold, før det det pakkes ned.](http://begrep.difi.no/SikkerDigitalPost/1.2.0/forretningslag/meldingsstorrelse) 

For eksempel kan dette returneres i TransportOkKvittering?

**Comment by fredrikbach** [comment]
@aberner Litt usikker, men er ikke dette kanskje en SDP grensesnitt sak? Tenker at det kan jo være like aktuelt for avsendere som går rett på SDP APIet? Litt unaturlig at dette kalkuleres av biblioteket? Takk.

**Comment by aberner** [comment]
@fredrikbach @austrheim 

Avsender bør hente ut størrelsen på dokumentpakken før den sendes for å vite hva omtrentlig kostnad vil bli. Altså det er ikke nødvendig å endre API't i digital post og at postkasseleverandør returnerer dette i forretningsmeldingen.

Men Avsendere bruker sikker-digital-post-klienten for å skape dokumentpakken.
Avsender har dermed ikke et forhold til dokumentpakken og kan dermed ikke finne ut hva størrelsen er.

For Avsendere som ikke bruker sikker-digital-post-klienten så lager de selvsagt dokumentpakken selv og kan finne ut av størrelsen selv.

Jeg oppfatter at  @austrheim bruker klient-biblioteket og dermed aldri har et forhold til dokumentpakken før den sendes.

Jeg oppfatter at @austrheim ønsker at klient-biblioteket gjør det mulig å få hentet ut dokumentpakkestørrelsen før dokumentpakken krypteres og sendes.

**Comment by austrheim** [comment]
Kremt. Litt dårlig beskrivelse her.

Ja, jeg bruker klient-biblioteket.

Ja, jeg ønsker å få (via klient-biblioteket) vite dokumentpakkestørrelsen.

Det er (i mitt hode) noe som bør regnes ut av SDP API'et eksponeres i TransportOkKvittering.

Grunnen til at jeg trenger tallet er et ønske om rapportering, og avsjekk mot innkommende faktura (når den tid kommer) derav forslag om at dette gjøres i API'et for å være "sikker" på at tallene blir korrekt.

**Comment by asjafjell** [comment]
@aberner: Er vi enig om at dette er en SDP-grensesnittimplementasjon, og ikke noe som bør kalkuleres i biblioteket?

**Comment by aberner** [comment]
Jeg oppfatter ikke at @austrheim sier at dette skal håndteres av postkasseleverandørene som mottar og dekrypterer dokumentpakken.
Jeg oppfatter at @austrheim sier at det bør regnes ut av SDP klient API'et.

Dokumentpakken skapes før den sendes av Avsender, det vil si at klient API'et. 
Det betyr at Avsender, det vil si klient API'et, kjenner til størrelsen på dokumentpakken før den sendes.

Jeg ser ikke behovet for at dokumentpakken må krypteres, sendes via meldingsformidler til postkasseleverandørene som så dekrypterer dokumentpakken før vi henter ut størrelsen på dokumentpakken.

Mener dere faktisk at Postkasseleverandørene bør regne ut og returnere størrelsen på dokumentpakken tilbake til Avsender?

Jeg forstår ikke hvorfor ikke avsendere (altså klient API't) kan regne ut denne dokumentpakke størrelsen før den sendes.

**Comment by austrheim** [comment]
Jeg sier at jeg bryr meg katten i hvor dette regnes ut. Det kan godt regnes ut i klienten så lenge resultatet blir det samme som leverandøren regner seg frem til.

Det tallet jeg vil ha må uansett regnes ut for intern bruk av postkasseleverandør, så jeg hadde en teori om at de burde ha returnert dette som en del av forretningskvitteringen -> "Yep, mottatt, vi lagrer xxx  byte".

Hvis en utregning i klienten blir like nøyaktig og jeg slipper å få spørsmål om hvorfor regningen vi får fra postkasseleverandør ikke stemmer med internrapporten, flott! Hvis ikke ... la postkasseleverandører returnere tallet.

**Comment by asjafjell** [comment]
Her er vi helt enige @austrheim. Det gir derfor mest mening at dette kommer i responsen og at vi tilbyr å eksponere ut denne informasjonen gjennom biblioteket. Vi ønsker ikke at klienten skal bli et endepunkt med masse forretningslogikk og tilstand. Å tilby dette tallet i forretningskvitteringen er derfor det som gir mest mening.

**Comment by aberner** [comment]
ok.

@austrheim @asjafjell Dette vil ikke prioritert implementert i postkassene de neste 6 - 12 månedene.
Dere for da vurdere om det er praktisk for nå realisere i klient biblioteket.

Jeg mener forsatt at det er i klientbiblioteket det skal regnes ut.

jeg oppfattet at dette er en ønskelig utvidelse for å kontrollere regningene fra postkasseleverandørene.
En slik kontroll får du ikke dersom du velger at postkasseleverandøren regner ut størrelsen på pakken for deg. Da kan de rapportere en større volum enn dere mener dere sender og også sende faktura som er i henhold til disse rapporterte størrelsene.

**Comment by tormel** [comment]
Jeg er enig i at det er klientbiblioteket som burde ha et forhold til hva den sender fra seg..    men det er nesten slik at klientbiblioteket og meldingformidleren  må komme til enighet om dette.. er de uenige her burde hele forsendelsen bli stoppet med feilmelding om at her er det tvil om hva som faktisk skal leveres

**Comment by aberner** [comment]
Dokumentpakken er signert og kryptert og kan ikke endres på veien. Så det skal ikke være mulig å endre den underveis. Så det er vel ikke problemstillingen.
Ut i fra det skal det dermed også være lite rom feil anderledes tolkning av størrelsen på dokumentpakken hos avsender og postkasseleverandør.

Behovet slik jeg oppfattet det var:

- mulighet for Avsender å etterprøve fakturaen som avsender får fra difi.

For å kunne etterprøve fakturaen bør Avsender lagre ned størrelsen på dokumentpakkene som Avsender sender fra seg. 

Diskusjonen her går altså ut på om Avsender skal lagre ned dokumentstørrelsen før den sendes fra seg eller om Postkasseleverandøren skal returnere dokumentpakkestørrelsen i kvitteringen.

Det kan skje begge steder. Dersom postkasseleverandør skal gjøre dette må Difi bestille denne endringen hos begge postkasseleverandører. Det vil ikke bli bestilt med det første. Så dersom en Avsender ønsker denne endringen nå må det legges inn i klientbiblioteket.

**Comment by tormel** [comment]
På kort sikt er det tilstrekkelig at dette legges inn i klientbiblioteket.

**Comment by asjafjell** [comment]
Dette er blitt fikset og er tilgjengelig i [1.5.5952.17675](https://www.nuget.org/packages/difi-sikker-digital-post-klient/1.5.5952.17675)
