### ISSUE TITLE
Dokumentnavn på vedlegg får feil navn i postkassen

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#120]
Lager en forsendelse med vedlegg. Navn (ikke filnavnet) blir satt til "vedlegg 1" og "vedlegg 2".
Resultatet i postkassen blir at brukeren blir presentert med at vedleggene har følgende navn:
«ib3j3wod.3iy» og «akbga3jc.ldw» eller «reaoeajz.ih5» og «n4ljqnhc.514» altså titlene er uleselige og forskjellige fra hver forsendelse.

**Comment by kristianenge** [comment]
Dette kan testes i beta fom. versjon #1.3.5787.18057
