### ISSUE TITLE
Feil bruk av ValiderTransportkvittering

### ISSUE THREAD

**Issue by austrheim** [difi/sikker-digital-post-klient-dotnet#122]
TLDR: HentKvitteringOgBekreftForrigeAsync kaller ValiderTransportkvittering som feiler fordi det ikke dreier seg om en TransportKvittering men en ForretningsKvittering og gir diffus feilmelding når den _kan_ gi en korrekt feilmelding.

I 'HentKvitteringOgBekreftForrigeAsync' i [SikkerDigitalPostKlient](https://github.com/difi/sikker-digital-post-klient-dotnet/blob/master/Difi.SikkerDigitalPost.Klient/Api/SikkerDigitalPostKlient.cs#L251).

I exception håndteringen gjøres et kall til [ValiderTransportkvittering](https://github.com/austrheim/sikker-digital-post-klient-dotnet/blob/master/Difi.SikkerDigitalPost.Klient/Api/SikkerDigitalPostKlient.cs#L281). I denne metoden (ValiderTransportKvittering) havner jeg igjen i catch blokka og den kaller [KvitteringFactory.GetTransportKvittering](https://github.com/austrheim/sikker-digital-post-klient-dotnet/blob/master/Difi.SikkerDigitalPost.Klient/KvitteringFactory.cs#L78) som kaster igjen en XmlParseException med meldingen "Klarte ikke å finne ut hvilken type Transportkvittering som ble tatt inn. Sjekk rådata for mer informasjon. En mulig grunn til dette kan være at svar fra server har endret seg, eller at en feilaktig endring har blitt gjort."

Dette blir "feil".

I mitt tilfelle er problemet at det er noe krøll med krypteringen, så resultatet blir at ValiderTransportKvittering havner i catch delen, og der kjøres en KvitteringFactory.GetTransportKvittering (som skal sjekke at det er en korrekt meldingstype som undersøkes, og igjen skal wrappes i en SdpSecurityException hvis det er en transportOkKvittering), dette feiler da jeg har en gyldig forretningskvittering (bare med krøll på krypteringen). Og jeg ender opp med en totalt intetsigende feilmelding. Koden kan istedenfor finne ut hva som faktisk var feil, og jeg kunne få en vakker SdpSecurityException istedenfor.

**Comment by asjafjell** [comment]
Her har du fanget opp en liten rakker. Logikken i beste fall heller rotete, og er noe vi rydder opp i nå på i #119 . Denne skal være klar til release om ikke så alt for lenge. Den skal rydde opp i feilhåndteringen i `SikkerDigitalPostKlient`, men jeg klarer ikke å se på strak arm om den fikser ditt problem. 

Jeg gir beskjed når denne er ute og så kan du teste.

**Comment by austrheim** [comment]
Flott.

Også fint hvis jeg kunne fått en tentativ dato for (om så) en beta-versjon av den releasen...

Jeg mistenker at sertifikat-håndteringen er årsak til problemene vi har i test-miljøene. Vi har forøvrig en _veldig_ tight brannmur, så jeg håper sertifikat-verifiseringen håndterer at du har alle root sertifikatene lokalt.

Spørsmål (og svar gjerne med teskje). Hvor må difi sine sertifikat være installert for å få tjenesten til å fungere (som en temporær løsning helt til #119 lander), jeg har tydeligvis installert dem feil :)

**Comment by asjafjell** [comment]
Sertifikatene i kjeden er lagret lokalt. Ingen online oppslag her, så brannmur skal ikke være noe problem.

Når det gjelder hvorfor du må ha Difi sitt sertifikat lagret lokalt, så er det fordi vi gjør en match på det vi får inn i responsen fra Meldingsformidler med det vi har lagret lokalt. I det nye regimet matcher vi det ikke , vi bare ser om kjeden til sertifikatet er gyldig. Grunnen til at vi gjorde en match tidligere er bare et resultat av feiltolkning av hvordan Difi ville ha det implementert. 

Hvis du følger guiden i dokumentasjonen for å installere mottakersertifikat så skal den biten være i orden. For du får faktisk lastet inn sertifikatet siden du klarer å kjøre koden og får en respons, regner jeg med. Det skal ikke være mange dagene før denne er i gjennom. Vi må gjøre litt kvalitetskontroll internt før den går ut siden vi har gjort store endringer på akkurat dette. Om du er fysen på å sjekke med en gang, så kan du bare ta ned branchen `r_enhetstesterSertifikat` -- misvisende navn på branchen, men det er den som tar for seg den nye sertifikathåndteringen.

**Comment by aberner** [comment]
Men hvordan er det med OCSP oppslag. Det er kanskje det @austrheim sikter til. Avsendere må vel åpne for OCSP oppslag i forbindelse med sertifikatvalidering. Gjør klientbiblioteket dette innebygd, så må eventuelt dokumentasjonen beskrive hvilke brannmur åpninger som må være påplass for at OCSP oppslaget går igjennom.

**Comment by asjafjell** [comment]
OCSP-oppslag er utelatt i denne versjonen, da det er en større jobb.

**Comment by austrheim** [comment]
Hentet ned `r_enhetstesterSertifikat` og brukte resultatet fra den istedenfor nuget pakken.

Fungerte som snus. Det vil si, jeg fikk kontakt, skal teste med litt mer saklig bruk i løpet av dagen.

**Comment by asjafjell** [comment]
Flott å høre! @austrheim

**Comment by asjafjell** [comment]
Nå er r_enhetstesterSertifikat merget inn i master og kan hentes ned som  v1.3.5785.28389-beta, @austrheim. Beklager at denne har kommet litt sent, men vi har luket ut en del andre bugs vi har kommet over. Forhåpentligvis har ikke du plagdes med de samme. Det er produksjonskode, men legges ikke ut som release før vi har dokumentasjon for den.

**Comment by austrheim** [comment]
Fungerer ikke for meg (branchen alene fungerte fint).

Jeg ser det er en forskjell i `SertifikatkjedevalidatorFunksjoneltTestmiljø` imellom branch og [main](https://github.com/difi/sikker-digital-post-klient-dotnet/blob/master/Difi.SikkerDigitalPost.Klient/XmlValidering/SertifikatkjedevalidatorFunksjoneltTestmilj%C3%B8.cs), nemlig at i branchen inneholder X509ChainPolicy `VerificationFlags = X509VerificationFlags.AllowUnknownCertificateAuthority` noe den ikke gjør i Main.

Det vil si, i Main er faktisk [SertifikatkjedevalidatorFunksjoneltTestmiljø](https://github.com/difi/sikker-digital-post-klient-dotnet/blob/master/Difi.SikkerDigitalPost.Klient/XmlValidering/SertifikatkjedevalidatorFunksjoneltTestmilj%C3%B8.cs) og [SertifikatkjedevalidatorProduksjon](https://github.com/difi/sikker-digital-post-klient-dotnet/blob/master/Difi.SikkerDigitalPost.Klient/XmlValidering/SertifikatkjedevalidatorProduksjon.cs) identiske. Noe jeg antar er en feil?

**Comment by asjafjell** [comment]
Her har du spottet en bug vi fant sent i går, @austrheim. Ironisk nok i bugfiksen. Vi har jobbet med å få klientbiblioteket til å ignorere sertifikater som ligger lokalt på maskinen. På sikt vil de noe være forskjellige når får inn revokeringssjekk. Vi skal ta en kikke på dette nå, og få ut en fiks med en gang.

**Comment by asjafjell** [comment]
@austrheim: Vi har litt problemer med å debugge din feil siden vi sender mot meldingsformidler som Posten, så vi får ikke sjekket dette problemet før vi har fått tak i et testsertifikat for en annen bedrift. Hvis du har mulighet til å sjekke hva du får som _kjedestatus_ i _Sertifikatkjedevalidator_ (både _Status_ og _StatusInformation_).

**Comment by austrheim** [comment]
{System.Security.Cryptography.X509Certificates.X509ChainStatus}
    Status: UntrustedRoot
    StatusInformation: "A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.\r\n"
    m_status: UntrustedRoot
    m_statusInformation: "A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.\r\n"

**Comment by austrheim** [comment]
Og som sagt, hvis du legger til `chain.ChainPolicy.VerificationFlags = System.Security.Cryptography.X509Certificates.X509VerificationFlags.AllowUnknownCertificateAuthority`i `SertifikatkjedevalidatorFunksjoneltTestmiljø` fungerer det utmerket.

Og igjen. Hvis det ikke skal legges til, hvorfor finnes da både `SertifikatkjedevalidatorFunksjoneltTestmiljø`og `SertifikatkjedevalidatorProduksjon` hvis de skal være identiske.

**Comment by asjafjell** [comment]
Det er ikke så rask fiks som du foreslo, @austrheim, fordi vi ikke ønsker å godta selvsignerte sertifikater. 

Men nå er fiksen ute i v1.3.5791.24495-beta. Tar du en sjekk på den og ser om det fungerer nå? Så får vi lukket denne og prodsatt.

**Comment by austrheim** [comment]
Takk, den ser ut til å fungere:)
