### ISSUE TITLE
.NET 4.0 versjon

### ISSUE THREAD

**Issue by toreveiseth** [difi/sikker-digital-post-klient-dotnet#125]
Ønsker å benytte dette biblioteket sammen med BizTalk server 2010 som kjører på .NET 4.0 versjon. Finnes det en versjon for .NET 4.0 eller er det mulig å lage en egen variant?

**Comment by asjafjell** [comment]
Hei, @toreveiseth! Hovedgrunnen til at vi kjører versjon 4.5 er støtte for `async` og `HttpClient`. Dette gir oss mye kortere utviklingstid og smidighet for en del designvalg. 

.NET4.0 er fra 2010, altså 5 år gammelt, mens .NET4.5 er 3 år gammelt. Vi har tatt en vurdering og funnet at 4.5 er den beste løsningen mtp. støtte for avsendere, samtidig som vi gjør det mye lettere for oss selv.

Jeg har tatt en rask kikk på [biztalk server 2010 R2 release notes](http://blogs.msdn.com/b/biztalk_server_team_blog/archive/2012/08/29/announcing-microsoft-biztalk-server-2010-r2-ctp-release.aspx) og de viser at R2 støtter .NET4.5 og gir bedre ytelse og en del nye funksjoner.  Det ser ikke ut til at det er mye arbeid knyttet til en slik oppgradering.

**Comment by toreveiseth** [comment]
Skulle ønske vi kunne oppgradert i en fei, men så enkelt er det nok ikke :-) Planen er at vi skal ha ny versjon av BizTalk på lufta til sommeren, men før den tid må vi finne en alternativ løsning. Har ikke noe lyst til å installere .NET4.5 på dagens servere av frykt for å ødelegge for andre applikasjoner.

**Comment by asjafjell** [comment]
Det er for øyeblikket ingen planer om å lage en klient med .NET4.0-støtte. Dette er ikke gjort i en håndvending. Ettersom vi har måttet implementere en del av signeringen selv for .NET4.5, så er det ikke sikkert at vi klarer å få den til å fungere med .NET4.0.

**Comment by toreveiseth** [comment]
Vi har oppe til vurdering å fremskynde planlagt oppgradering av BizTalk. Tar med oss dette som et moment i denne prosessen. Takk for utfyllende svar så langt.

**Comment by asjafjell** [comment]
Flott! Håper det går fint for seg. Husk at det er bare å spørre om du trenger mer info på denne her.
