### ISSUE TITLE
Stilsett på dokumentasjon brekker i header

### ISSUE THREAD

**Issue by kristianenge** [difi/sikker-digital-post-klient-dotnet#127]
La merke til at logoen på [SDP](http://difi.github.io/sikker-digital-post-klient-dotnet/) ser ødelagt ut. 

![image](https://cloud.githubusercontent.com/assets/3032364/10933437/c43c7d62-82d8-11e5-8e81-24146ea1410d.png)

Er det gjort noen endringer på Difi sitt stilsett?

**Comment by kjorlaug** [comment]
Det gjort nokre små endringar i CSS og HTML for å få betre UU-støtte. Skal fikse

**Comment by asjafjell** [comment]
Flott at du tar tak i det! Sjekk gjerne ut en egen branch og lag pull-request når det er klart, @kjorlaug.

**Comment by kristianenge** [comment]
Vi fikset dette med å endre fra <h1> til <span>. Er ute nå.
