### ISSUE TITLE
Hvordan kan jeg følge med på nye releaser av klientbiblioteket?

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#138]
Hei,

Vi har mange som bruker klientbiblioteket. Hvordan kan de enkelt følge med på nye releaser uten at de må følge med på alle endringer på github?
brukere av biblioteket har behov for å få et varsel når nye releaser blir lagt ut med informasjon om hva som er gjort. 
Dette for at vi effektivt skal kunne få rullet ut de nye releasene til avsendere.

Jeg har sett på en mulig oppskrift/løsning for avsendere slik at de kan få til dette.
Det er bruk av www.sibbell.com

og oppskriften er som følger:

- Opprett en bruker på github: http://github.com/
- Gå inn å velg å stjerne de(t) prosjekt(ene) som er relevant
  - (Star er et lite symbol opp til høyre)
- Gå til sibbel: https://sibbell.com
 - Velg å autorisere sibbel for tilgang til din github konto
 - Velg synkronisering av de prosjekter som du har stjernet
 - Velg å få en epost av sibbel 

Spørsmålet er:

- Er oppskriften over ok? eller er det andre og enklere måter å få løst dette på?
- Hvordan kan vi enklest dokumentere dette ovenfor brukerne av biblioteket? kan vi legge inn denne oppskriften som en del av dokumentasjonen knyttet til bibliotekene for digital post?

**Comment by kristianenge** [comment]
Jeg tenker at de som er aktive brukere av Github(og mest sannsynlig utviklere) vil bruke den innebygde 'Watch' funksjonaliteten. For alle andre ser dette ut som en bra løsning! 

Jeg har ikke testet Sibbell før, men så lenge de ikke endrer hva som er gratis så burde det holde til dette formålet. 

Vi kan enten dokumentere det på github.io eller legge det på begrep.difi.no. Det som slår meg er at hvis de allerede er inne på github.io så er det kanskje ikke de vil nå?

**Comment by aberner** [comment]
ok.
jeg har oppfattet at man for java har maven kommandoen:
```
mvn versions:display-dependency-updates
```

Men har man tilsvarende for .net? slik at de som bruker dette får det inn i sitt bygg.

Jeg oppfatter at github sin Watch funksjon gir alt for mye informasjon og ikke er det brukerne av biblioteket ønsker. Da får man informasjon om alle endringer i et bibliotek.

**Comment by klakegg** [comment]
Hva med å følge med på RSS som er innebygget funksjonalitet i Github?
https://github.com/difi/sikker-digital-post-klient-dotnet/releases.atom

**Comment by kristianenge** [comment]
Atom feeden og en reader som videresender til email er også en løsning. 

Alle releasene blir jo sluppet på NuGet og .NET sin ekvivalent til mvn version:display-dependency-updates må være [Package manager console] : Get-Package -updates

**Comment by aberner** [comment]
ok, da er denne utfordringen egentlig håndtert godt nok via NuGet og package manager for alle utviklere.
Så er det å kunne få  varsel på e-post mer for  personer som følger og er ansvarlige for systemer men som ikke selv utvikler.

takk for gode svar.

jeg tror jeg skal forsøke skrive noe veiledningsmateriell til avsendere om dette, så tenker jeg at dokumentasjonen på klientbiblioteket eventuelt kunne minnet utviklere på å alltid holde seg oppdatert via nuget/package manager eventuelt.
