### ISSUE TITLE
Feil i ToStringWithUtcOffset-konverteringen i SikkerDigitalPost.Klient

### ISSUE THREAD

**Issue by Landstad** [difi/sikker-digital-post-klient-dotnet#141]
Det virker som om ToStringWithUtcOffset-konverteringen som ikke fungerer helt som en håper(?).
 
Det jeg sikter til ligger i DLL-en min (SikkerDigitalPost.Klient.dll, v1.2.5578.26671):
https://github.com/difi/sikker-digital-post-klient-dotnet/blob/e3a490b6c6228e90fe210f10f9cccbd4318ecd4a/Difi.SikkerDigitalPost.Klient/Extensions/DateTimeExtensions.cs
 
Dette blir brukt i linje 90 i DigitalPostElement.cs:
https://github.com/difi/sikker-digital-post-klient-dotnet/blob/eeddca7901ddf8f9af58edbb1c940643d32a4dd5/Difi.SikkerDigitalPost.Klient/Envelope/Forretningsmelding/DigitalPostElement.cs
 
Vedlagt er en Program.cs som viser problemet. 
[Program.zip](https://github.com/difi/sikker-digital-post-klient-dotnet/files/88638/Program.zip)

Her skjer følgende:
 
1.       DateTime.Now produserer datetime.-versjonen som skaper feilen.
2.       Den blir først rettet midt i ToStringWithUtcOffset():
const string fullFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fff";
 
string date = dateTime.ToString(fullFormat);
3.       Men følgende linje skaper altså trøbbel igjen:
return dateTime.ToString(String.Format("{0}{1}", date, offset.ToString(format)));
 
Resultatet av kjøringen blir derfor:
![bilde1](https://cloud.githubusercontent.com/assets/1122224/12290357/9d52c55e-b9e1-11e5-8f5c-90ab6e63945d.jpg)

Om noen har et forslag til hvordan jeg lett kan løse det på min side (altså på utsiden av dll-en), tar jeg gjerne imot forslag. Dersom jeg prøver å endre Language Neutral i bildet under, kjører ikke DLL-en siden signaturen da ikke lengre stemmer.
![bilde2](https://cloud.githubusercontent.com/assets/1122224/12290386/c6d248c8-b9e1-11e5-8a6b-c376c2005aa7.jpg)

**Comment by asjafjell** [comment]
Hei, @Landstad.

Takk for fyldig og god beskrivelse og kjørende eksempel, men jeg ser ikke umiddelbart hva det er som er problemet her. Poenget med `ToStringWithUtcOffset` er å legge på hvor mange timer man er fra UTC, og det fungerer den fint for så langt jeg kan se. Du skrev ikke direkte hva som ikke fungerte slik som det skal for deg, så kunne du utdypet litt mer?

**Comment by Landstad** [comment]
Hei.

Jeg får en exception siden DateTime.now() hos meg produserer dato på et annet format enn det som godtas (altså, type <ns9:virkningstidspunkt>2015-12-16T09:33:00.000+01:00</ns9:virkningstidspunkt>).

Det blir først korrigert midt i "ToStringWithUtcOffset()" i følgende linje: const string fullFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fff";

Etterpå blir korrigeringen ødelagt av "return dateTime.ToString(String.Format("{0}{1}", date, offset.ToString(format)));".

Resultatet på min side er at det blir forsøkt å sende virkningstidspunkt på format a la "2015-11-20T15.04.41.862+01.00", som igjen ikke blir validert og jeg får ikke sendt post.


Exceptionen ser slik ut:
Sending av forsendelse feilet under validering. Feilmelding: SikkerDigitalPost.Domene.Exceptions.XmlValidationException:  Validering av Xml feilet: Envelope validerer ikke:               Validation error: It is an error if there is a member of the attribute uses of a type definition with type xs:ID or derived from xs:ID and another attribute with type xs:ID matches an attribute wildcard.
Feilen over er ikke noe vi håndterer, og er heller ikke årsaken til at validering feilet
                Validation error: The 'http://begrep.difi.no/sdp/schema_v10:virkningstidspunkt' element is invalid - The value '2015-11-20T15.04.41.862+01.00' is invalid according to its datatype 'http://www.w3.org/2001/XMLSchema:dateTime' - The string '2015-11-20T15.04.41.862+01.00' is not a valid DateTime value.

   at SikkerDigitalPost.Klient.SikkerDigitalPostKlient.ValiderForretningsmeldingEnvelope(XmlDocument forretningsmeldingEnvelopeXml, XmlDocument manifestXml, XmlDocument signaturXml)
   at SikkerDigitalPost.Klient.SikkerDigitalPostKlient.Send(Forsendelse forsendelse)

**Comment by asjafjell** [comment]
Da forstår jeg. Du får faktisk en Exception her. Det er litt underlig. Jeg sitter selv med engelsk Windows, og da vil en `DateTime.Now` gi: _1/13/2016 1:19:09 PM_. Da metoden kun bruker selve objektet og ikke gjør parsing på en string, skal ikke språkinnstillinger ha noe å si. 

Jeg har kikket en stund på denne metoden for å prøve å skjønne hva som gjør at du får en feil. Det blir gjort en eksplisitt formatering, Men hvis du ser på siste linje
`  return dateTime.ToString(String.Format("{0}{1}", date, offset.ToString(format)));` så er alt innenfor `dateTime.ToString` allerede den gyldige datoen som skal returneres, så hvorfor det fungerer i utgangspunktet er litt underlig. 

Vi tenker uansett å gjøre om den formateringen til å bruke DateTime.UtcNow, men må gjøre litt testing først. Ny release på dette kommer snarlig!

**Comment by asjafjell** [comment]
Hvis du installerer 1.4.5857.16268-beta som ligger på Nuget, så skal dette problemet være fikset. Rop ut og si hvordan det går.

**Comment by Landstad** [comment]
Hei. Tester gjerne ut dette. Ligger det en DLL jeg kan erstatte den DLL-en
jeg bruker i dag noe sted?

tor. 14. jan. 2016 kl. 09.10 skrev Aleksander Sjåfjell <
notifications@github.com>:

**Comment by asjafjell** [comment]
Hei! Pakken blir distribuert gjennom .Nuget og hvordan du installerer den ser du [her på Nuget](https://www.nuget.org/packages/difi-sikker-digital-post-klient/1.4.5857.16268-beta).

**Comment by Landstad** [comment]
Hei.

Jeg lastet ned nuget, avinstallerte gamle referanser og la til nye.
Refaktorerte løsningen min og gjorde antagelser (Istedenfor å skrive inn
meldingsformidlerURI skriver en nå "Miljø.Produksjonsmiljø" når en
oppretter klientkonfigurasjon, "Behandlingsansvarlig" har blitt renamet til
"Avsender" osv) slik at løsningen kom opp å gå igjen.

Får fortsatt følgende feilmelding:

Det oppsto én eller flere feil. - Inner: System.Exception: Sending av
forsendelse feilet under validering. Feilmelding:
Difi.SikkerDigitalPost.Klient.Domene.Exceptions.XmlValidationException:
 Validering av Xml feilet: Envelope validerer ikke: Validation error: Det
er en feil hvis det finnes et medlem av attributtet som bruker en
typedefinisjon med typen xs:ID eller avledet fra xs:ID og et annet
attributt med typen xs:ID tilsvarer et attributtjokertegn.
Validation error: Elementet
http://begrep.difi.no/sdp/schema_v10:virkningstidspunkt er ugyldig -
Verdien 2016-01-19T14.37.51.406+01.00 er ugyldig i henhold til datatypen
http://www.w3.org/2001/XMLSchema:dateTime - Strengen
2016-01-19T14.37.51.406+01.00 er ikke en gyldig DateTime verdi.

   ved
Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.ValiderForretningsmeldingEnvelope(XmlDocument
forretningsmeldingEnvelopeXml)
   ved
Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.&lt;SendAsync>d__0.MoveNext()
   ved
Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.&lt;SendAsync>d__0.MoveNext()

Mvh
Andreas S. Landstad

man. 18. jan. 2016 kl. 17.52 skrev Aleksander Sjåfjell <
notifications@github.com>:

**Comment by aberner** [comment]
Hei,

Jeg oppfatter at dataformatet du bruker er feil.
Korrekt format er slik: 2016-01-15T09:08:50.000+01:00
Verdien du bruker er: 2016-01-19T14.37.51.406+01.00 

Som du ser så har du punktum der det skal være kolon.

**Comment by aberner** [comment]
Formatet på feltet virkningstidspunkt er definert her: https://www.w3.org/TR/xmlschema-2/#dateTime

**Comment by asjafjell** [comment]
Da vet vi at det et locale-problem og ikke et direkte kodeproblem, om vi kan kalle det det. Det er klientbiblioteket som gjør en feil her, @aberner, ikke @Landstad. Bruker av klientbiblioteket skal ikke forholde seg til dette. Vi må ta en titt og se hva som kan føre til at det blir slik. Ser at Xsd-feilmeldingene som kommer er på norsk, så er nok noe med det.

**Comment by Landstad** [comment]
Jepp, jeg viser at det er et localeproblem (og en løsning på problemet!!) i
eksempelet i issuet jeg lagde..

tir. 19. jan. 2016 kl. 15.01 skrev Aleksander Sjåfjell <
notifications@github.com>:

**Comment by asjafjell** [comment]
Jeg har testet med forskjellige locales og DateTime.Now.ToString("O") gir alltid samme uansett locale. Kan du gå inn på installerte nugetpakker på prosjektet og sjekke versjon av klienten som er installert? _(Project -> Manage Nuget Packages -> Installed Packages)_ Jeg vil ha hele versjonsnummeret. Takk!

**Comment by Landstad** [comment]
Hei, beklager, jeg ser at jeg kanskje har feil versjon (1.4.5806.28577).
Jeg får prøve å installere én gang til og prøve igjen. Melder tilbake.

tir. 19. jan. 2016 kl. 15.31 skrev Aleksander Sjåfjell <
notifications@github.com>:

**Comment by asjafjell** [comment]
Flott, da ordner det seg Bare huk av for _Include prerelease_, så ordner det seg.

**Comment by Landstad** [comment]
Fikk nå testet med pre-releasen. Får en ny feilmelding:

Noe galt skjedde. Teknisk feilmelding: Det oppsto én eller flere feil. -
Inner: System.Exception: Sending av forsendelse feilet under validering.
Feilmelding:
Difi.SikkerDigitalPost.Klient.Domene.Exceptions.XmlValidationException:
 Validering av Xml feilet: Envelope validerer ikke: Validation error: Det
er en feil hvis det finnes et medlem av attributtet som bruker en
typedefinisjon med typen xs:ID eller avledet fra xs:ID og et annet
attributt med typen xs:ID tilsvarer et attributtjokertegn.

   ved
Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.ValiderForretningsmeldingEnvelope(XmlDocument
forretningsmeldingEnvelopeXml)
   ved
Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.&lt;SendAsync>d__0.MoveNext()
   ved
Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.&lt;SendAsync>d__0.MoveNext()

Har ikke debugget det og får ikke tid til å gjøre det med én gang. Om dere
har noe umiddelbart forslag til hva det kan være tar jeg gjerne imot tips,
hvis ikke ser jeg på det siden.

tir. 19. jan. 2016 kl. 15.38 skrev Aleksander Sjåfjell <
notifications@github.com>:

**Comment by asjafjell** [comment]
Det er merkelig at du får så masse feilmeldinger her på XML-valideringen. Dette har vi ikke vært borti tidligere. Du kan teste å sette locale på maskinen til en-US (English - United States) under Region settings. Det kan hende at det fikser det.

**Comment by Landstad** [comment]
Å bytte locale på maskinen fungerte! :)

tir. 19. jan. 2016 kl. 16.03 skrev Aleksander Sjåfjell <
notifications@github.com>:

**Comment by Landstad** [comment]
... Så byttet jeg config til å gå mot produksjonsmiljø.

Jeg får da feilmeldingen under. Det virker som om det er fordi det er
mismatch mellom den nye SikkerDigitalPostKlienten og hva Meldingsformidler
forventer? Skal jeg nå gå mot en nyere/annen meldingsformidler?

One or more errors occurred. - Inner:
Difi.SikkerDigitalPost.Klient.Domene.Exceptions.SdpSecurityException: Kan
ikke finne påkrevet element
'/env:Envelope/env:Header/wsse:Security/wsu:Timestamp' i svar fra
meldingsformidler.
   at
Difi.SikkerDigitalPost.Klient.XmlValidering.Responsvalidator.ResponsInneholderPåkrevdeNoder(String
elementXPath, XmlNodeList&amp; nodes)
   at
Difi.SikkerDigitalPost.Klient.XmlValidering.Responsvalidator.ValiderSignaturelementer()
   at
Difi.SikkerDigitalPost.Klient.XmlValidering.Responsvalidator.ValiderHeaderSignatur()
   at
Difi.SikkerDigitalPost.Klient.XmlValidering.Responsvalidator.ValiderTransportkvittering(GuidUtility
guidUtility)
   at
Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.SikkerhetsvalideringAvTransportkvittering(XmlDocument
kvittering, XmlDocument forretningsmelding, GuidUtility guidUtility)
   at
Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.&lt;SendAsync>d__0.MoveNext()

tir. 19. jan. 2016 kl. 16.33 skrev Andreas Ståleson Landstad <
landstad.andreas@gmail.com>:

**Comment by asjafjell** [comment]
Flott! Det får bli en midlertidig fiks å bytte locale mot maskinen. 

Nå ser det ut som du får samme feilmelding som tidligere, men nå antar jeg det er en parsefeil som rapportert i #140. Der var løsningen: _Feilen du opplever er at sertifikatet du bruker og orgnummer du setter i Databehandler ikke matcher_ Husk at du må bruke produksjonssertifikat når du går mot produksjon.

**Comment by Landstad** [comment]
Hehe, du har rett. Jeg hadde hardkodet inn thumbnailen til testsertifikatet
i det nye miljøet.. Takk for hjelpen!

ons. 20. jan. 2016 kl. 10.53 skrev Aleksander Sjåfjell <
notifications@github.com>:

**Comment by asjafjell** [comment]
Flott at det ordnet seg til slutt! Vi kan jo ikke gi oss før det er fikset. Jeg lukker denne og så får du opprette ny issue om du støter på flere problemer.
