### ISSUE TITLE
Feil locale gir feilmeldinger ved XML-validering

### ISSUE THREAD

**Issue by asjafjell** [difi/sikker-digital-post-klient-dotnet#144]
Ref issue #141, så oppstår det en del problemer når locale er satt feil. Klarer ikke reprodusere feilen selv, men det er åpenbart en løsning å endre locale på maskinen. Hva skal til for å gjenprodusere?

**Comment by kristianenge** [comment]
Er dette fortsatt et problem @Landstad ?

**Comment by Landstad** [comment]
Hei,

Jeg har ikke utviklingsmiljøet tilgjengelig nå, så jeg får dessverre ikke
hentet ned siste og testet.

En lakmustest vil være å sjekke caset som ligger ved issuet.

For vår del endret vi locale for å kunne jobbe videre.

A

man. 18. apr. 2016 kl. 15.02 skrev Kristian <notifications@github.com>:

**Comment by asjafjell** [comment]
Vi har testet med eksemplet som du gav, og dette er ikke et problem nå som `DateTimeExtensions.ToStringWithUtcOffset` følger ISO8601. Den standarden er den samme uansett locale som er satt på maskinen.
