### ISSUE TITLE
Problemer med bekreftelse av opprettede kvitteringer

### ISSUE THREAD

**Issue by Landstad** [difi/sikker-digital-post-klient-dotnet#149]
Vi har testet det som ble løst i issue #145 .

Det virker ikke som om dette fungerer.

Gitt en Forretningskvittering fk som vi får fra dere i form av en leveringskvittering:

Dersom vi erstatter:
1 (fungerer): sdpk.Bekreft(fk);

med
2 (fungerer ikke): sdpk.Bekreft(new Leveringskvittering(fk.KonversasjonsId,fk.BodyReferenceUri,fk.DigestValue));

får vi ikke samme resultat. Med 1) får vi bekreftet meldingen og den forsvinner fra HentKvittering-stacken, men med 2) forblir kvitteringen i stacken.

Har dere noen kodelinjer som viser hvordan dere fikk dette til å fungere da dere testet det?

**Comment by asjafjell** [comment]
Ser på denne nå, og så skal vi få løst den så raskt som mulig.

**Comment by asjafjell** [comment]
Jeg har nå kikket på denne og klarer ikke å gjenskape situasjonen. 

```
var enkelForsendelse; //Her lager du forsendelsen
var sdpklient; //Her lager du klienten 

var kvitteringsforespørsel = new Kvitteringsforespørsel(enkelForsendelse.Prioritet, enkelForsendelse.MpcId);

var kvitteringFørSending = await sdpklient.HentKvitteringAsync(kvitteringsforespørsel);

if (kvitteringFørSending is TomKøKvittering)
{
    Trace.WriteLine("Køen er tom før sending!");
}

var transportkvittering = await sdpklient.SendAsync(enkelForsendelse);

Thread.Sleep(2000);
var kvittering = await sdpklient.HentKvitteringAsync(kvitteringsforespørsel);

Forretningskvittering nyKvittering = null;
if (kvittering is Leveringskvittering)
{
	Trace.WriteLine("Køen hadde en Leveringskvittering");
    var leveringskvittering = (Leveringskvittering) kvittering;
    nyKvittering = new Leveringskvittering(leveringskvittering.KonversasjonsId, leveringskvittering.BodyReferenceUri, leveringskvittering.DigestValue);

}

if (kvittering != null)
{
    sdpklient.Bekreft(nyKvittering);
}

Thread.Sleep(2000);

var nesteKvittering = await sdpklient.HentKvitteringAsync(kvitteringsforespørsel);

if (nesteKvittering is TomKøKvittering)
{
    Trace.WriteLine("Køen er tom etter bekreftelse!");
}
```

**Comment by Landstad** [comment]
Hei,

Har du sjekket om køen fremdeles er tom etter fem minutter med koden du skriver over? I så fall, kan det være noen forskjell på Async-operasjonene og de jeg bruker i koden under?

Dersom jeg har én kvittering i stacken og kjører koden under først en gang, og deretter på nytt seks minutter senere, ligger samme kvittering i køen begge ganger:

                var kvitteringsForespørsel = new Kvitteringsforespørsel(Prioritet.Normal, <din mpcIdHer>);

                Kvittering kvittering = null;
                try
                {
                    kvittering = sdpk.HentKvittering(kvitteringsForespørsel);
                }
                catch (Exception e)
                {
                    //Slettet..
                }

                if (kvittering is Leveringskvittering)
                {
                    Leveringskvittering lk = (Leveringskvittering)kvittering;
                    sdpk.Bekreft(new Leveringskvittering(lk.KonversasjonsId, lk.BodyReferenceUri, lk.DigestValue));
                }
                else if (kvittering is TomKøKvittering)
                {
                    //Ingen kvitteringer.
                    break;
                }
            }

**Comment by Landstad** [comment]
Har nå forsøkt også med async-operasjonene, men det ser ikke ut til at det hjelper. Gjerne bekreft/avkreft at kvitteringen hos deg ikke er der igjen seks minutter senere.

Jeg:
1. Sender en forsendelse
2. Kjører koden under (som er en kopi av din minus teststegene dine)
3. Kjører koden igjen etter seks minutter.

Får da opp samme kvittering i debuggeren ved begge kjøringer.

            var kvitteringsforespørsel = new Kvitteringsforespørsel(Difi.SikkerDigitalPost.Klient.Domene.Enums.Prioritet.Normal, mpcId);

            var kvittering = await sdpklient.HentKvitteringAsync(kvitteringsforespørsel);

            Difi.SikkerDigitalPost.Klient.Domene.Entiteter.Kvitteringer.Forretning.Forretningskvittering nyKvittering = null;
            if (kvittering is Difi.SikkerDigitalPost.Klient.Domene.Entiteter.Kvitteringer.Forretning.Leveringskvittering)
            {
                var leveringskvittering = (Difi.SikkerDigitalPost.Klient.Domene.Entiteter.Kvitteringer.Forretning.Leveringskvittering)kvittering;
                nyKvittering = new Difi.SikkerDigitalPost.Klient.Domene.Entiteter.Kvitteringer.Forretning.Leveringskvittering(leveringskvittering.KonversasjonsId, leveringskvittering.BodyReferenceUri, leveringskvittering.DigestValue);
                sdpklient.Bekreft(nyKvittering);
            }

**Comment by asjafjell** [comment]
Hei! Det du gjør stemmer nok. Jeg skal teste litt mer. Det som skjer hvis du henter en kvittering og ikke bekrefter den, er at den kommer tilbake på køen etter fem minutter. Jeg skal sjekke litt logger og se hva som foregår. Takk for detaljerte eksempler!

**Comment by asjafjell** [comment]
Feilen er lokalisert, og en fiks kommer så raskt som mulig.

**Comment by asjafjell** [comment]
Test med [denne releasen](https://www.nuget.org/packages/difi-sikker-digital-post-klient/1.5.5877.28530-beta) og sjekk om alt er som det skal være da.

**Comment by Landstad** [comment]
Til eventuelle interesserte: Denne versjonen (som inlkuderer MeldingsId) fungerte.

**Comment by asjafjell** [comment]
Flott at det løste seg!
