### ISSUE TITLE
Feil i dokumentasjonen - tag som ikke blir tolket korrekt

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#151]
På dokumentasjonsidene her: http://difi.github.io/sikker-digital-post-klient-dotnet/v1.5/

finner man nederst følgende avsnitt:

´´´
.NET-klient for integrasjon mot Sikker digital post-tjenesten
{% for dok in site.v1_5 %} {% if dok.id %}
{{dok.title}}
{{dok.content}}
{% endif%} {% endfor %}
´´´

Jeg tror dette kommer av at Jekyll ble oppdaterte 01. Februar. 
Problemet kommer av at det nå tydeligvis blir satt default verdi til id i index.html filen.  
Det bør fungere ved å endre fra ´´´id´´´ med ´´´pageid´´´.

Dette bør fungere dersom følgende blir endret:

´´´{% if dok.id %}''' til f.eks:  ´´´ {% if dok.pageid %}´´´

og på hver side omtrent slik:

Fra: '''id: hvordankommeigang''' til: '''pageid: hvordankommeigang'''

**Comment by asjafjell** [comment]
Hei. Vi vet hva som er galt, og det blir fikset nå. Takk for info.

**Comment by asjafjell** [comment]
Dette skal nå være fikset, så i løpet av noen minutter er det nok oppdatert.
