### ISSUE TITLE
'System.NullReferenceException' i Difi.Oppslagstjeneste.Klient.dll

### ISSUE THREAD

**Issue by johnviggo** [difi/sikker-digital-post-klient-dotnet#153]
Jeg sliter med følgende feilmelding ved forsøk på å kjøre metoden "HentPersoner"  i Oppslagstjenesten.

> System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Difi.Oppslagstjeneste.Klient
  StackTrace:
       at Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.SendEnvelope(AbstractEnvelope envelope)
       at Difi.Oppslagstjeneste.Klient.OppslagstjenesteKlient.HentPersoner(String[] personidentifikator, Informasjonsbehov informasjonsbehov)
....

Har brukt http://difi.github.io/oppslagstjeneste-klient-dotnet/ som utgangspunkt for følgende kode: https://gist.github.com/johnviggo/51e6cb01e7d861dad478

Jeg har blitt litt kastet inn i dette men får samme feilmelding på eksisterende test-kode som er skrevet. Tenkte bare jeg skulle starte på nytt for å forstå litt mer hva som skjer, men blir altså stoppet på samme vis.

Jeg bruker versjon 1.0.5637.22318 av Oppslagstjeneste-klient

**Comment by asjafjell** [comment]
Hei, @johnviggo og takk for fyldig og god beskrivelse med Gist og versjonsnummer. Jeg skulle gjerne fått sett mer av StackTrace for å se hva som faktisk er `null`. Kunne du gitt meg det?

**Comment by asjafjell** [comment]
Lukker denne. Fortsett tråd i [Oppslagstjeneste.Issues](https://github.com/difi/oppslagstjeneste-klient-dotnet/issues/33), da den hører hjemme der, @johnviggo
