### ISSUE TITLE
En fault som svar på Send gir valideringsfeil

### ISSUE THREAD

**Issue by SandGrainOne** [difi/sikker-digital-post-klient-dotnet#156]
I dette tilfelle inneholder forsendelsen en avsender som ikke er gyldig/registrert. Dette gir en 400 Bad Request respons med følgende body: 
https://gist.github.com/SandGrainOne/29e10997ac2261c78918f3fce1d007be

Dette tolker klienten som en TransportFeiletKvittering. Ingen overraskelser så langt.

Det som derimot er uheldig er at når klienten validerer respons body (rådata) så er det en forventning i koden om at innholdet er en gyldig TransportKvittering og ikke en Fault. Feilen som oppstår har følgende informasjon.

```
Type : Difi.SikkerDigitalPost.Klient.Domene.Exceptions.SdpSecurityException, Difi.SikkerDigitalPost.Klient.Domene, Version=1.5.5878.15667, Culture=neutral, PublicKeyToken=683b8efceae684a6
Message : Kan ikke finne påkrevet element '/env:Envelope/env:Header/wsse:Security/wsu:Timestamp' i svar fra meldingsformidler.
Source : Difi.SikkerDigitalPost.Klient
Help link : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ResponsInneholderPåkrevdeNoder(System.String, System.Xml.XmlNodeList ByRef)
HResult : -2146233088
Stack Trace :    at Difi.SikkerDigitalPost.Klient.XmlValidering.Responsvalidator.ResponsInneholderPåkrevdeNoder(String elementXPath, XmlNodeList& nodes)
   at Difi.SikkerDigitalPost.Klient.XmlValidering.Responsvalidator.ValiderSignaturelementer()
   at Difi.SikkerDigitalPost.Klient.XmlValidering.Responsvalidator.ValiderTransportkvittering(GuidUtility guidUtility)
   at Difi.SikkerDigitalPost.Klient.Api.SikkerDigitalPostKlient.<SendAsync>d__0.MoveNext()
```

Dette er meget uheldig siden det skjuler den egentlige årsaken til at forsendelsen mislyktes.

**Comment by aberner** [comment]
Dette er en feil som ofte oppstår både i testfaser og ved produksjonssetting.
Det er kritisk at avsendere som bruker .net klienten har mulighet til å få den reelle feilen med feilmeldingen slik at de vet hva de skal gjøre.
Denne feilen påvirker forvaltningen av løsningen uheldig, siden vi får inn flere spørsmål fra virksomheter som lurer på hva de gjør feil.

**Comment by asjafjell** [comment]
Jeg oppdaget tilfeldigvis dette problemet allerede på torsdag, så har allerede startet fiksen for denne. Skal være ordnet opp i i løpet av kort tid.

**Comment by asjafjell** [comment]
Dette skal være fikset i [1.5.5952.26500-beta](https://www.nuget.org/packages/difi-sikker-digital-post-klient/1.5.5952.26500-beta). Test det ut og kom med tilbakemelding, så får vi lukket denne @SandGrainOne.

**Comment by SandGrainOne** [comment]
Testet ok.
