### ISSUE TITLE
Problemer med å legge til flere nuget pakker

### ISSUE THREAD

**Issue by fmj** [difi/sikker-digital-post-klient-dotnet#167]
Vi skal bruke oppslagstjeneste og sikker digitalpost. Har lagt til pakkene fra nuget som følger:

```XML
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="difi-oppslagstjeneste-klient" version="5.1.5952.22633" targetFramework="net45" />
  <package id="difi-sikker-digital-post-klient" version="1.6.5962.22680" targetFramework="net45" />
</packages>
```` 

Etter å ha oppdatert pakkene til siste versjon så får jeg følgende feil:
![image](https://cloud.githubusercontent.com/assets/2693481/15014939/3b879252-1209-11e6-9a4c-4f5bfa30f221.png)

Det ser ut som oppslagtjeneste biblioteket er linket mot en annen versjon av Difi.FellesUtility enn Difi.SikkerDigitalPost.Klient slik at det ikke er mulig å bruke begge nugetpakkene samtidig:

Oppslagstjeneste: 
![image](https://cloud.githubusercontent.com/assets/2693481/15014970/73530c3e-1209-11e6-833c-b24fb1cd35e3.png)

SikkerDigitalPost:
![image](https://cloud.githubusercontent.com/assets/2693481/15014991/8de0809a-1209-11e6-9674-d5c479727c32.png)

Er det mulig å få harmonisert pakkene slik at de bruker samme fellesbibliotek eller er det nuget som har et problem?

**Comment by asjafjell** [comment]
Harmonisering pågår, så en fiks på dette kommer snarlig. Bare følg med på dette issuet, så får du beskjed når det er fikset.

**Comment by fmj** [comment]
Ser at grunnen til at det ikke fungerer er at dere har endret navn til engelsk:
![image](https://cloud.githubusercontent.com/assets/2693481/15015197/bae87538-120a-11e6-8e1c-dc9547caac50.png)

Hvor lang tid tar en fiks @asjafjell ?

**Comment by fmj** [comment]
Det ser ut som det eneste som må til er å endre denne baseklassen til den nye versjonen. Er dette noe som kan fikses relativt kjapt?

![image](https://cloud.githubusercontent.com/assets/2693481/15015402/eeeabdf4-120b-11e6-9e9e-49606f6324cc.png)

**Comment by asjafjell** [comment]
Problemet her er at vi har lastet inn .dll feil i .nuget-pakkene, slik at avhengighetene blir implisitt. Dette fører til runtime-feil. Vi kommer til å sørge for at avhengighetene er eksplisitte, slik at man kan se at de er avhengig av forskjellige pakker. Dette  blir fikset så snart som mulig.

**Comment by fmj** [comment]
Vi er nødt til å ha oppslagstjenestedll, utsending og felleskomponenter lastet inn i samme prosjekt. Det er da viktig at det er samme felleskomponent som er i bruk for både oppslagstjeneste og utsending. Det er mao viktig å endre baseklassen for miljø til ny versjon av oppslagstjeneste slik at dette kompilerer. Usikker på hva du mener med kommentaren over.. Jeg vil ikke tro at det hjelper å sette eksplisitte avhengigheter da det ikke er lov å laste samme dll 2 ganger som avhengighet til et prosjekt.

**Comment by asjafjell** [comment]
Jeg skjønner problemstillingen og det du sier er delvis rett. Det er ikke mulig å direkte laste inn to dll-er i samme prosjekt. Men ved å sette eksplisitte avhengigheter på SDP og OT så kan vi sette en range med versjoner som godtas. I ditt tilfelle vil ikke dette fungere, og da må vi se til andre løsninger. 

Jeg var litt uklar når jeg sa definitivt  ja til harmonisering av avhengigheter, for dette blir nok ikke gjort til enhver tid. Det vil være tidspunkt hvor de ikke er like. Heldigvis er det en løsning for dette, og det er å legge inn aktuell .dll i GAC. Test gjerne oppskriften på [msdn.microsoft.com](https://msdn.microsoft.com/en-us/library/dkkx7f79(v=vs.110).aspx) og kom med tilbakemelding.

**Comment by fmj** [comment]
Da går det slik:

![image](https://cloud.githubusercontent.com/assets/2693481/15112060/ff4ac1ba-15eb-11e6-9ea4-d9889a1f0550.png)

Begge assemblies lagt i gac.

**Comment by fmj** [comment]
Tror uansett at det vil være problemer med å laste 2 versjoner av samme dll i samme appdomene. Kan du bare bygge oppslagstjenesten med rett versjon av baseklasse for miljø (den engelske) og gi meg en ny dll? Forøvrig så er det nok en tanke å prøve å sørge for at felleskomponenter er bakoverkompatible..

**Comment by asjafjell** [comment]
Det finnes mange eksempler på biblioteker som har avhengigheter som linker til inkompatible versjoner av et bibliotek, så dette problemet vil du kunne treffe på andre steder. Man kan aldri vite kombinasjonen av biblioteker som blir brukt og det kan aldri være et krav at alle skal være i samme versjon til enhver tid. Hvorfor det ikke fungerer for deg er litt uklart. Det er mulig det må litt mer konfigurasjon til.

Når det er sagt så har vi gjort alle bibliotekene eksplisitt avhengige, og da har dette løst seg i ditt tilfelle. Oppgrader til nyeste versjon av SDP og OT og gi tilbakemelding på om det fungerer.

**Comment by fmj** [comment]
Da fungerer det som det skal (i hvert fall kompileringsmessig). Det som skulle til var at denne baseklassen ble endret:

![image](https://cloud.githubusercontent.com/assets/2693481/15113443/9dc3571e-15f4-11e6-97fa-6deea0315c67.png)

Det bør da bare være og lukke saken..
