### ISSUE TITLE
Sikkerhetsnivå

### ISSUE THREAD

**Issue by pereilif** [difi/sikker-digital-post-klient-dotnet#170]
Hei,

Selv om jeg i DigitalPostInfo spesifiserer at det skal brukes Sikkerhetsnivå3 så kreves det likevel ekstra pålogging i Digipostkassen til brukeren for å kunne lese dokumentet: "Avsenderen krever at du logger inn på et annet sikkerhetsnivå for å åpne brevet".
Er det noe mer som må angis for å få sendt på Sikkerhetsnivå3, eller blir ikke denne verdien tatt hensyn til lenger? 
Tester i "FunksjoneltTestMiljø" med siste nuget-pakken

**Comment by aberner** [comment]
Det kreves alltid bruk av ID-porten ved åpning av brev fra det offentlige.
Så dersom du velger å logge på med en annen innlogging enn ID-porten vil du bli bedt om å logge på en gang til når du skal åpne brevet.

**Comment by pereilif** [comment]
Takk for svar. Har bare logget på med MinId, så da forklarer jo det saken

**Comment by asjafjell** [comment]
Det er ikke rart at du ble forvirret, @pereilif. Dokumentasjonen i koden er helt feil og vil bli fikset.
