### ISSUE TITLE
Nuget for sikker-digital-post bør ligge under organisasjonskonto for Difi

### ISSUE THREAD

**Issue by asjafjell** [difi/sikker-digital-post-klient-dotnet#172]
Det bør lages en konto for Difi på [Nuget](www.nuget.org) som har alle klientbiblioteker som driftes og eies av Difi. Hvis dette blir gjort bør det sjekkes hvordan tilgangsstyring kan gjøres for utviklere, slik at de kan ha tilgang til kontoen. Det kan være lurt å starte [her](https://docs.nuget.org/create/managing-package-owners).

**Comment by aberner** [comment]
@klakegg noe som du kan bidra med her ? har vi dette for andre prosjekter?

**Comment by klakegg** [comment]
Jeg tror @ekorra må trå til her. Vi bruker per i dag ikke Nuget på noen andre prosjekter.

**Comment by asjafjell** [comment]
Det er uheldig å la issues som dette henge så lenge som dette. Dette er noe som melder seg når det trenger seg på, så arkiverer denne inntil videre.

**Comment by aberner** [comment]
@asjafjell Difi har nå en konto på nuget. brukernavn: "difi"
