### ISSUE TITLE
Bruksområde for fødselsnummer

### ISSUE THREAD

**Issue by asjafjell** [difi/sikker-digital-post-klient-dotnet#174]
Hvorfor kreves det at det sendes inn fødselsnummer ved sending? Brukes det av  Eboks?

**Comment by aberner** [comment]
Dette fødselsnummeret legges inn i manifest.xml fila i dokumentpakken og gir en knyting til innbygger som vedvarer over tid og som ikke er avhengig av postkasseleverandør.

**Comment by asjafjell** [comment]
Det gir mening. Takk for info!
