### ISSUE TITLE
Støtte for ASP.NET Core uten .NET framework?

### ISSUE THREAD

**Issue by losviko** [difi/sikker-digital-post-klient-dotnet#177]
Ligger det noen planer her for støtte av ASP.NET core uten å bruke hele .NET framework? Det ville jo kunne gi mange mulighet for open source cross-platform programmer.

**Comment by asjafjell** [comment]
Vi har kikket litt på det og på nåværende tidspunkt er det ingen planer for dette, men på sikt er dette absolutt noe vi ønsker å se nærmere på.

**Comment by asjafjell** [comment]
Vi ønsker å løsrive oss helt fra Windows som plattform og har snust på Project Rider. Så snart det prosjektet er mer modent så kan det godt hende at en konvertering til DotNetCore blir påbegynt, men vi ønsker nok å ta to fluer i en smekk her.

**Comment by asjafjell** [comment]
Dette er målbildet for bibliotekene, og vi har alltid fokus på å komme oss opp på høyere versjoner, men det er dessverre mange versjoner opp til NET core. Jeg lukker denne og noterer at det er et ønske.
