### ISSUE TITLE
Testmiljø bruker produksjonsertifikater mens klientbibliotek forventer testsertifikater

### ISSUE THREAD

**Issue by leifhv** [difi/sikker-digital-post-klient-dotnet#178]
Prøver å bruke klientbiblioteket mot miljø FunksjoneltTestmiljøVerifikasjon1 men får da 'SecurityException: Sertifikatet i responsen er ikke gyldig' i OppslagstjenesteValidator.ValidateResponseCertificate.

Har testet å validere sertifikatet jeg får tilbake i min egen kode og validering feiler da riktig nok mot FunksjoneltTestmiljøSertifkater....men validering går bra mot Produksjonssertifikater.

Har fått beskjed om at det er produksjonssertifikater som brukes også i testmiljø, men klientbiblioteket ser ut til å forvente testsertifikater der:

```
namespace Difi.Oppslagstjeneste.Klient
{ 
     public class Miljø 
     { 
         internal Miljø(Uri url, CertificateChainValidator certificateChainValidator) 
...
         public static Miljø FunksjoneltTestmiljøVerifikasjon1 => new Miljø( 
             new Uri("https://kontaktinfo-ws-ver1.difi.no/kontaktinfo-external/ws-v5"), 
             new CertificateChainValidator(CertificateChainUtility.**FunksjoneltTestmiljøSertifikater**()) 
             ); 
```

Hvordan skal man få klientbibliotektet til å godta produksjonssertifikatene som returneres fra oppslagstjenesten når man kjører mot miljø FunksjoneltTestmiljøVerifikasjon1 ?

**Comment by aberner** [comment]
informasjonen: "Har fått beskjed om at det er produksjonssertifikater som brukes også i testmiljø" er nok feil.
kan ikke se at det stemmer, det er test-virksomhetssertifikater som brukes i alle testmiljøer.

**Comment by leifhv** [comment]
Det var det jeg fikk beskjed om og min egen testkode gir samme konklusjon. Responsesertifikatet validerer ok som produksjonssertifikat, men ikke som testsertifikat:

//Hent ut sertifikatet vi fikk i responsen fra testtjenesten
var cert = new X509Certificate2(certBytes);
            
//Dette går bra...sertifikatet vi fikk når kalte testtjensten godtas som produksjonssertifikat
var validProdCert = new CertificateChainValidator(CertificateChainUtility.**ProduksjonsSertifikater**()).ErGyldigSertifikatkjede(cert);

//Dette går **ikke** bra....sertifikatet vi fikk når vi kalte testtjenesten godtas **ikke** som testsertifikat
var validTestCert = new CertificateChainValidator(CertificateChainUtility.**FunksjoneltTestmiljøSertifikater**()).ErGyldigSertifikatkjede(cert);


Hvis det faktisk er testsertifikat som brukes i testmiljøet burde det jo ikke validere riktig som produksjonssertifikat?

**Comment by aberner** [comment]
beklager men jeg er litt i villrede her, forsøker du å bruke https://github.com/difi/sikker-digital-post-klient-dotnet for å sende digital post, eller bruker du https://github.com/difi/oppslagstjeneste-klient-dotnet for integrasjon mot oppslagstjenesten?

hvilket sertifikat er det du har problemer med? er det SSL sertifikater for oppkobling eller virksomhetssertifikatene som du har hentet fra oppslagstjenesten for kryptering av posten til digital post?

(ellers fint å få noe mer info enn ditt alias, (navn og firma tilhørighet er alltid fint på github profilen))

**Comment by leifhv** [comment]
Argh, beklager...jeg er på feil plass. Klikket bare på linken jeg fikk på mail fra difi om hvor jeg skulle registere issuen og den pekte hit. Lukker denne og oppretter ny for oppslagstjenesten.
