### ISSUE TITLE
De synkrone metodene på API-et går i deadlock når de kalles fra en ASP.NET-webapplikasjon

### ISSUE THREAD

**Issue by andreasnilsen** [difi/sikker-digital-post-klient-dotnet#179]
Samme problem som beskrevet for oppslagstjeneste-klienten ser ut til å eksistere i SDP-klienten.
F.eks. ved kall til SikkerDigitalPostKlient.Send(...). Vil anta at måten å fikse det på er den samme.

Dette er ikke noen showstopper for meg, da jeg uansett kan benytte de asynkrone metodene (det var egentlig greit å finne stedet i koden jeg hadde glemt å bytte til asynkront kall :) )

Se tidligere registrert oppslagstjeneste-issue for en detaljert beskrivelse:
[De synkrone metodene på API-et går i deadlock når de kalles fra en ASP.NET-applikasjon](https://github.com/difi/oppslagstjeneste-klient-dotnet/issues/68)

**Comment by asjafjell** [comment]
Beklager voldsomt sent svar på denne her. Fiks kommer med neste release.

1.

**Comment by asjafjell** [comment]
Denne er fikset i [1.7.6024.27199](https://github.com/difi/sikker-digital-post-klient-dotnet/releases/tag/v1.7.6024.27199)
