### ISSUE TITLE
Opprettelse av digital postkasse i testmiljøer

### ISSUE THREAD

**Issue by kimbell** [difi/sikker-digital-post-klient-dotnet#180]
Jeg jobber med helsenorge.no, og vi skal prøve ut funskjonalitet rundt digitale postkasser. Det første jeg tenkte å se på er opprettelse av postkassen, slik at vi har noe å sende ting til. 

Vi har allerede tilgang til Difi sitt kontaktregister i forskjellige miljøer. Når vi gjør kall mot disse så ser jeg at dataene vi får tilbake mangler sertifikat og postakasse info; tenkte jeg skulle prøve å få noen verdier inn her. 

Jeg logget meg på https://brukerprofil-ver2.difi.no med personnummeret til en av testbrukerne våre. Når jeg klikker på knappen for digital postkasse, så får jeg 404. 

Hvordan kan vi få opprettet postkasse for våre testbrukere?

**Comment by aberner** [comment]
hei,
for slike spørsmål om testing osv. er det best å sende spørsmålet til idporten@difi.no
Tekniske spørsmål om klientbiblioteket.
Du får lenker til korrekte testmiljøer for e-boks og digipost fra idporten@difi.no
