### ISSUE TITLE
Hva skjer ved bruk av utskriftstjenesten i verifikasjonsmiljø?

### ISSUE THREAD

**Issue by andreasnilsen** [difi/sikker-digital-post-klient-dotnet#182]
Har forsøkt å spørre om dette via difi support-mail, men har ikke fått svar der i løpet av 2 uker, så tillater meg å "spamme" med spørsmålet her:

* Hvordan fungerer bruk av utskriftstjenesten i verifikasjonsmiljøet? Stopper det etter leveransekvittering?  Eller er det noe som faktisk fysisk skrives ut og sendes?
* I forlengelsen av dette spørsmålet; koster bruk av utskriftstjenesten i verifikasjonsmiljøet noe?

**Comment by SimonsUnikaNamn** [comment]
Hej, 

i testmiljön så betyder leveringskvitteirng att printleverantör skapat en PDF vilket räknas som "printing". Denna kan vi hämta och levera ut om någon vill se hur leveransen skulle se ut.

Nej det kostar ingenting att bruka testmiljön.

mvh

Simon

**Comment by andreasnilsen** [comment]
Takk for raskt svar!
