### ISSUE TITLE
Klarer ikke å bruke siste versjon av oppslagstjensten

### ISSUE THREAD

**Issue by kimbell** [difi/sikker-digital-post-klient-dotnet#185]
Jeg prøver å bruke nuget pakkene for både oppslagstjenesten og digital post. Ønsker selvsagt å bruke siste versjon av disse pakkene. Problemet er at disse ikke virker mot samme versjon av fellesbibliotekene deres.

``` 
difi-oppslagstjeneste-klient 5.3.6024.16371
   difi-felles-utility-dotnet (>= 0.6.6008.19059 && < 0.7.0) 
   api-client-shared (>= 1.0.5941.27271 && < 1.1.0) 
```
```
difi-sikker-digital-post-klient 1.10.0.25393 
   difi-felles-utility-dotnet (>= 0.8.0.27738 && < 1.0.0) 
   api-client-shared (>= 1.0.5968.19413 && < 2.0.0) 
```
Dersom jeg oppgraderer difi-felles-utility-dotnet  til siste versjon, så går det greit for difi-sikker-digital-post-klient men denne er inkompatibel for difi-oppslagstjeneste-klient.

Hvordan skal jeg få brukt siste versjon av ting? 

PS. Bruken av autogenererte nummer for deler av versjonen er en uting. Gjør det veldig vannskelig å se forholdet mellom to versjoner.

**Comment by asjafjell** [comment]
Hei og takk for en god problembeskrivelse! 

Vi er midt i en opprydding når det gjelder avhengigheter, så oppdatert versjon av `difi-felles-utility-dotnet` kommer snarlig for `difi-oppslagstjeneste-klient-dotnet`. 

Når det gjelder versjonsnummerering så har vi gått over til å strengt følge [SemVer](http://www.semver.org) for Major, Minor og Patch, men for å kunne støtte vårt regime for automatisk produksjonssetting av nye klienter så vil det siste tuppelet være et autogenerert nummer. Dette vil også gjøre at det blir litt lettere å lese. Vi har dessverre ikke klart å finne en bedre løsning enn dette ettersom det ikke er noen måte å erstatte et bibliotek som allerede er sluppet til _Nuget_.

**Comment by kimbell** [comment]
Når tror dere at de nye pakkene er tilgjengelig? Snakker vi timer/dager/uker?

**Comment by asjafjell** [comment]
Vi snakker timer/dager. Ser på det nå.

**Comment by asjafjell** [comment]
Kan du teste [5.4.0.27761-alpha](https://www.nuget.org/packages/difi-oppslagstjeneste-klient/5.4.0.27761-alpha) og komme med tilbakemelding?

**Comment by kimbell** [comment]
Nå har jeg fått lagt inn alpha versjonen av oppslagstjenesten og siste versjon av post. Så langt har ikke nuget klaget, og vår eksisterende funksjonalitet ser ut til å fungere som forventet. 

Skal nå begynne å grave i hvordan post biten faktisk skal kodes, så vi får se hvordan det går.

**Comment by asjafjell** [comment]
Flott. Lukker denne da. Ny produksjonsrelease kommer nå.
