### ISSUE TITLE
Støtte for sending av flere dokumenter - ref versjon 1.2.4 av grensesnitt dokumentasjonen 

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#187]
Klientbiblioteket må oppdatere XSD i henhold til versjon 1.2.4 av grensesnitt dokumentasjonen.
https://github.com/difi/begrep-SikkerDigitalPost/releases/tag/1.2.4

Dette for å kunne støtte sending av mer enn 10 vedlegg.

Endringen er planlagt realisert i løpet av desember 2016 i produksjon så klient biblioteket må ha en ny versjon med støtte for dette i god tid før dette.

**Comment by asjafjell** [comment]
Den eneste endringen som må gjøres i klientbiblioteket for at dette skal fungere er å oppdatere XSD til å ha `vedlegg.maxOccurs=200`, så den endringen er triviell. Siden dette ikke støttes av backend så vil responsen være `Parsefeil: Kan ikke parse SDPManifest`. Dette er uheldig for brukere, så denne bør nok realiseres i backend først.

**Comment by aberner** [comment]
fint om klientbiblioteket kan oppdateres når backend oppdateres i testmiljøet, slik at funksjonaliteten er tilgjengelig samtidig som backend oppgraderes.

**Comment by asjafjell** [comment]
Det fikser vi selvfølgelig, @aberner! 💃

**Comment by asjafjell** [comment]
Denne ble nå sluppet i v[2.0](https://github.com/difi/sikker-digital-post-klient-dotnet/releases/tag/v2.0.0.0). Det er foreløbig kun støttet mot _difitest/qaoffentlig_, men fra et klientperspektiv er dette implementert, så jeg lukker bare denne.
