### ISSUE TITLE
Kan SikkerDigitalPostKlient.HentKvitteringOgBekreftAsync returnere TransportFeiletKvittering? I så fall logges den ikke

### ISSUE THREAD

**Issue by andreasnilsen** [difi/sikker-digital-post-klient-dotnet#188]
Under feilsøk i vår klientkode for uthenting av kvitteringer, ser vi at vi ikke har tatt høyde for at SikkerDigitalPostKlient.HentKvitteringOgBekreftAsync kan returnere TransportFeiletKvittering.

Jeg ser at dere har tatt høyde for at dette i Testklienten : https://github.com/difi/sikker-digital-post-klient-dotnet/blob/master/Difi.SikkerDigitalPost.Klient.Testklient/Program.cs#L115

Vår mistanke er at ved SAML-feil EBMS:0103 (PolicyNoncompliance, angivelig fra bruk av feil sertifikat), blir dette oversatt til en TransportFeiletKvittering av tjenesten/operasjonen for å hente ut kvittering?

I så fall hadde det vært fint om klienten logget dette i HentKvitteringOgBekreftAsync  https://github.com/difi/sikker-digital-post-klient-dotnet/blob/master/Difi.SikkerDigitalPost.Klient/Api/SikkerDigitalPostKlient.cs#L265

**Comment by asjafjell** [comment]
Heisann!  Jeg skjønner ikke helt hva du mener, så kunne du skrevet om spørsmålet i avsnitt tre? Er dette på noen måte knyttet til #176 hvor du fortsatt har problemer? En TransportKvittering vil bare komme i retur om Meldingsformidleren svarer med en feil på Transportnivå. Ellers vil feil som ugyldig sertifikat kastes ut av klienten og må håndteres av brukeren av biblioteket.

**Comment by andreasnilsen** [comment]
Hei

Kort fortalt lurer vi på følgende:
* Kan HentKvitteringOgBekreftAsync returnere TransportFeiletKvittering? (Dette har du vel allerede svart bekreftende på)
* Hvis ja, kan dere endre loggingen i https://github.com/difi/sikker-digital-post-klient-dotnet/blob/master/Difi.SikkerDigitalPost.Klient/Api/SikkerDigitalPostKlient.cs#L265 til å også logge disse? Det spilte oss et puss i feilsøkingen at disse ikke ble logget av klienten, mens alle andre typer kvitteringer ble det.

Dette er ikke direkte relatert til #176.

**Comment by asjafjell** [comment]
Da henger jeg litt mer med på hva du mener. Det virker fornuftig å gjøre dette også for `Transportkvittering`. Dette er en relativt liten endring, men vi har andre issues som må ta først, så her er det bare å komme med en Pull Request om dere ønsker det tidligere.

**Comment by andreasnilsen** [comment]
Ja, det er ikke noen big deal. Skal se om jeg kan få hostet opp en PR i løpet av uka.

**Comment by rocketfarmsteinar** [comment]
@andreasnilsen @asjafjell Hei - er dette eit behov som finnes enno?

**Comment by asjafjell** [comment]
Det var jeg som forvaltet det tidligere, og siden det er dere som nå forvalter, @rocketfarmsteinar, så er nesten dette en avgjørelse dere får ta. Dette er fortsatt en svakhet i loggingen og bør fikses.

**Comment by rocketfarmsteinar** [comment]
@asjafjell Takk for tilbakemelding

**Comment by aknutsen** [comment]
Logging er nå utbedret i versjon 2.0.4.
