### ISSUE TITLE
Klienten validerer forretningskvitteringer mot meldingsformidlersertifikat istadenfor postkasseleverandørsertifikat 

### ISSUE THREAD

**Issue by 3150ihe** [difi/sikker-digital-post-klient-dotnet#195]
Hei!

Har en bruker som ikke får validert kvittering fra eBoks etter at de oppgraderte til siste versjon av klienten. Versjon 2.0.0, siste fra NuGet:

Trur dette er ein config feil hos hos avsender. Ser ut som om de prøver å validere kvitteringer fra eBoks med nøkkelen til digipost.

Her er mailen som bler sendt meg:

Nå fungerer det meste, bortsett fra at vi får følgende feil av og til fra HentKvittering (tekst fortsetter under): 
 
 
"Sertifikatet som ble mottatt i responsen er ikke gyldig. Grunnen er 'UgyldigSertifikat', med melding 'Sertifikat med Subject 'SERIALNUMBER=996460320, CN=E-BOKS AS, OU=Operation 1, O=E-BOKS AS, C=NO' og Thumbprint 'FEB6EE2E0C38C92FF380882F4856313CDB633802' er ikke utstedt til organisasjonsnummer '984661185'. Dette vil skje om sertifikatet er utstedt til en annen virksomhet eller hvis det ikke er et virksomhetssertifikat. Virksomhetssertifikat kan skaffes fra Buypass eller Commfides.'"
 
Den sikter til thumbnail FEB6EE…, men det er ikke en thumbnail maskinen jeg sitter på nå og tester med har noe forhold til (jeg har sjekket og maskinen har ingen sertifikater installert med den thumbnailen).
 
SikkerDigitalPostKlienten som brukes for å hente kvitteringer er tvert imot satt opp med følgende sertifikat (snippen under er hentet ut samtidig som snip over i debugger) 

    
![feilmelding](https://cloud.githubusercontent.com/assets/7995504/22734747/129e1e90-edf7-11e6-961e-9b09d5e685fc.jpg)

**Comment by rocketfarmsteinar** [comment]
Hei @3150ihe 

Takk for beskjed - vi skal sjå på dette og melde tilbake.

**Comment by rocketfarmsteinar** [comment]
Det ser ut som om avsender forventer at alle kvitteringer skal signeres av meldingsformidler mens meldingsformidler videresender meldinger som signert av eBoks og Digipost. Digipost fungerer "tilfeldigvis" fordi dei signerer med virksomhetssertifikat utstedt til samme orgnr som meldingsformidler.

Vi prioriterer å rette feilen og vil publisere ny versjon til Nuget når dette er gjort.

**Comment by 3150ihe** [comment]
Hei!
Lurer på status. Vi blir purret av avsender som lurer på om vi finner mulig feil og når dei kan forventa den blir retta.

**Comment by rocketfarmsteinar** [comment]
Hei igjen.

Vi publiserer ny versjon så snart vi får nødvendige tilganger til å publisere på Nuget. Skal purre på dette.

**Comment by aberner** [comment]
@difi/posten-norge-as-write må få overlevert nødvendig tilganger til @rocketfarmsteinar slik at ny versjon kan publiseres.

**Comment by asjafjell** [comment]
Som beskrevet i #172 så må Difi opprette en konto på Nuget. Inntil alle tilganger er gitt så kan en pakke publiseres manuelt.

**Comment by aberner** [comment]
@asjafjell brukernavn for Difi sin konto er: "difi", overfør eierskap til den brukeren.

**Comment by rocketfarmsteinar** [comment]
Etter diskusjon med @aberner har vi kommet til at vi treng meir tid på å vurdere validering av forretningskvitteringer - sjå og diskuter på #196

**Comment by Landstad** [comment]
@aberner og @rocketfarmsteinar:

Har dere noen forventet dato for utrulling av ny klient? Det er mye manuell jobb for politiets del så lenge vi ikke får hentet eBoks-kvitteringer.

**Comment by rocketfarmsteinar** [comment]
Hei @Landstad 

Versjon 2.0.1 er nettopp tilgjengelig på NuGet

**Comment by Landstad** [comment]
Topp @rocketfarmsteinar.

Da er ny versjon testet og produksjonssatt. Fungerer utmerket!
