### ISSUE TITLE
Behov for mulighet for oppkobling mot ytelsestestmiljø

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#197]
Jeg skal koble opp min klient mot meldingsformidler ytelsestestmiljøet. Hvordan kan jeg gjøre dette?

jeg ser i https://github.com/difi/sikker-digital-post-klient-dotnet/blob/131afe7757e4832ab87fff30016aa38e09eec1de/Difi.SikkerDigitalPost.Klient/XmlValidering/Milj%C3%B8.cs at det kun er referanse til funksjonelttestmiljø og produksjon.

Kan jeg overstyre dette på noen måte med den klienten jeg har nå?
kan dere levere en ny versjon som også gir mulighet for å velge ytelsestestmiljøet?

**Comment by rocketfarmsteinar** [comment]
Hei

Inntil vidare kan dette oppnås ved å overstyre eit av dei predefinerte miljøa slik som beskrevet under

```
Miljø.FunksjoneltTestmiljø.Url = new Uri("https://qa.meldingsformidler.digipost.no/api/");
//Miljø.FunksjoneltTestmiljø.GodkjenteKjedeSertifikater = ...; // Dersom dette fraviker fra det funksjonelle testmiljøet
var klientkonfigurasjon = new Klientkonfigurasjon(Miljø.FunksjoneltTestmiljø);
````

**Comment by rocketfarmsteinar** [comment]
Vi vil også komme tilbake med oppdatert versjon av biblioteket som inkluderer konfigurasjon for ytelsestest-miljøet.

**Comment by rocketfarmsteinar** [comment]
No er versjon 2.0.2 tilgjengelig via NuGet
