### ISSUE TITLE
Støtte for forsendelser med tittel på opp til 255 tegn

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#198]
ref: https://github.com/difi/begrep-SikkerDigitalPost/issues/191

Det er ønskelig at klientbiblioteket støtter endringen av feltene tittel og ikkeoffentligtittel.
Det er kun snakk om en mindre endring av XSD'n, klientbiblioteket må validere input i henhold til den.

endringen er planlagt satt i produksjon i juni 2017, klientbiblioteket ønskes oppdatert i løpet mai slik at det kan testes i forbindelse med endringen og være klar til å bli tatt i bruk så fort endringen er ute i produksjon.

**Comment by rocketfarmsteinar** [comment]
Hei Arne.

Den er grei. Tenker vi tek dette så kjapt det let seg gjere, men må komme tilbake til akkurat når.

Blir det ein ny versjon av XSD'en eller gjer de endring i den som alt er gjeldande?

**Comment by aberner** [comment]
jeg har gjort endringene på med denne commiten: https://github.com/difi/begrep-SikkerDigitalPost/pull/196
som du ser så har jeg ikke endret noe versjonsnummer eller lignende, kun gjort endringer i eksisterende. 
Siden jeg ser på dette som kun en utvidelse. håper at det ble riktig.
