### ISSUE TITLE
Problemer med sending av stort antall melding i parallell

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#200]
Avsender sender et stort antall meldinger i parallell med opp til 25 tråder ( har også testet med lavere antall  tråder f.eks.12) og opplever at de fleste meldingene feiler med følgende exception:

`ErrorMessages: System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host`

- Hva kan være årsaken til denne feilen`?
- Hvordan gjøres connection management? 
- Gjøres det forsøk på å gjenbruke connections?
- kan det være at .NET klienten ikke lukker trådene etter seg?

**Comment by aberner** [comment]
vi gjør kall direkte på HttpClient, og denne er det én instans av, slik at connections skal i teorien gjenbrukes. Den aktuelle koden for selve requestkjøringen finnes i RequestHelper.cs. For å verifisere om dette fungerer som det skal så er det mulig å bruke NETSTAT og se hva status på connections blir etter sending av et sett med meldinger. Se denne kilden for litt mer info om NETSTAT og gjenbruk av klienten.

**Comment by aknutsen** [comment]
Jeg fant denne, hvor det jfr kommentarene kan oppstå problemer dersom man prøver å bruke samme HttpClient fra flere tråder samtidig. Brukes samme instans av SikkerDigitalPostKlient på tvers av trådene eller har hver tråd sin egen instans?

https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by asjafjell** [comment]
Hvert nye instans av `SikkerDigitalPostKlient` vil opprette en ny `HttpClient`. Hensikten er at avsender skal bruke én instans av `SikkerDigitalPostKlient` for sending av alle meldinger og selv stå for trådhåndtering og sending gjennom klienten. `SikkerDigitalPostKlient` forholder seg ikke til tråder, og skal være trådsikker med mindre det finnes en bug.

**Comment by LasseStaffJensen** [comment]
OK, dette forklarer isåfall observerte feil. Vi lager p.t. en ny  `SikkerDigitalPostKlient` per kall:
`[ServiceBehavior(
        InstanceContextMode = InstanceContextMode.PerCall, 
        TransactionIsolationLevel = IsolationLevel.ReadCommitted,
        Namespace = "http://xxxxx/services/ServiceEngine/Correspondence/2009/10")]
`

**Comment by aberner** [comment]
Takk, dette løste problemer, men uansett så bør dette utbedres i klientbiblioteket slik at denne bruker connection pooling. Er ikke spesielt bra å måtte ha en felles instans på tvers av trådene.

**Comment by asjafjell** [comment]
Her er det nok noen misforståelser ute og går. At det brukes kun én instans av HttpClient betyr ikke at det ikke er connection pooling, og i motsetning til det som blir sagt her så mener jeg slik det er løst i dag er en god løsning. 

Som dokumentert på [MSDN](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.110).aspx):
_The HttpClient class instance acts as a session to send HTTP requests. An HttpClient instance is a collection of settings applied to all requests executed by that instance. In addition, every HttpClient instance uses its own connection pool, isolating its requests from requests executed by other HttpClient instances._

**Comment by LasseStaffJensen** [comment]
OK, uavhengig om `HttpClient` klassen faktisk støtter pooling teoretisk så fungerer jo dette ikke i praksis, slik diverse kilder på nett har vist (se post fra @aknutsen). Tenker det mest elegante er at `SikkerDigitalPostKlient ` skrives om til å benytte en felles (`static`) instans av `HttpClient` slik som nevnt i dokumentasjonen:

> HttpClient is intended to be instantiated once and re-used throughout the life of an application. Especially in server applications, creating a new HttpClient instance for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException  errors.


[se her](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client)

**Comment by asjafjell** [comment]
Jeg ser ikke forskjellen på å ha en statisk `HttpClient` som brukes for alle kall, og å ha en instans på en klasse som brukes gjennom hele livssyklusen (`SikkerDigitalPostKlient`), men det er mulig at `static`-modifieren løser noe _benhind the scenes_. For slik det er nå så lages ikke en ny `HttpClient` for hvert kall, noe det eksemplet ditt viser til @LasseStaffJensen.

**Comment by asjafjell** [comment]
Men samme feil skjer altså også når samme instans av `SikkerDigitalPost`-klient gjenbrukes for hvert kall?

**Comment by LasseStaffJensen** [comment]
Nei, ved gjenbruk så er dette fikset. Er, som du påpeker, ingen teknisk forskjell på de to variantene. Mitt poeng var vel mer at dette var APIets ansvar og ikke bruker av APIet, men så lenge det er dokumentert at man kun skal benytte en instans av  `SikkerDigitalPostKlient` så fungerer dette for oss.

**Comment by asjafjell** [comment]
Det er et godt poeng, @LasseStaffJensen. Hvis dette ikke kommer godt nok frem i dokumentasjonen så er dette noe Difi/Rocketfarm bør ta tak i. Ytelsen er merkbart bedre ved gjenbruk av klienten.

**Comment by aslakjo** [comment]
Når vi nå ser dette så skal vi ta en ekstra titt på dokumentasjon og api til Klienten og se om det kan bli enklere/mer intuitivt å bruke klienten som tenkt. Slik at andre ungår det samme. Vi putter dette på veikartet til neste release.

Takk til @asjafjell og @LasseStaffJensen for gode tilbakemeldinger og hjelp.

**Comment by aknutsen** [comment]
Har skrevet en paragraf i dokumentasjonen om hvordan klienten bør brukes, så lukker saken.
