### ISSUE TITLE
Branch for videre arbeid?

### ISSUE THREAD

**Issue by SindreNordbo** [difi/sikker-digital-post-klient-dotnet#202]
Hei,

jeg planlegger å implementere en endring (og submitte en PR) i dette klientbiblioteket ifm. https://github.com/difi/begrep-SikkerDigitalPost/pull/204 men jeg er litt usikker på hvilken branch jeg skal ta utgangspunkt i.

- `master` bygger ikke på AppVeyor (https://ci.appveyor.com/project/difi/sikker-digital-post-klient-dotnet/build/2.0.4-git655505d)
- `beta` er _veldig_ langt foran `master`
- `develop` er bak `master`

Er `beta` såpass stabil at dere planlegger å merge den inn i `master` ganske snart, slik at jeg kan ta utgangspunkt i koden der? Hvis ikke – kan dere sørge for at `master` bygger OK på CI-serveren slik at det er trygt å utvikle videre på den?

@difi/rocketfarm-write-forvaltning

**Comment by SindreNordbo** [comment]
Kanskje @aknutsen eller @rocketfarmsteinar kan hjelpe meg?

**Comment by rocketfarmsteinar** [comment]
@aslakjo Følger du denne?

**Comment by SindreNordbo** [comment]
Tillater meg å minne om denne. Har du anledning til å svare meg @aslakjo ?

**Comment by aslakjo** [comment]
Hei @SindreNordbo 

Jeg vil at du tar utgangspunkt i beta branchen. Denne skal om kort tid promoteres til master og dermed kommer den ut av beta også i nuget.

Beklager den lange ventetiden.

**Comment by SindreNordbo** [comment]
Flott, takk for tilbakemelding!
