### ISSUE TITLE
Overskrevet beta-branch

### ISSUE THREAD

**Issue by sindrebn** [difi/sikker-digital-post-klient-dotnet#210]
I forbindelse med videre utvikling av prosjektet er vi helt avhengig av en `beta`-branch som fungerer og er deploybar. På grunn av endringene som ble påbegynt i 2017 men ikke fullført er dette dessverre ikke tilfelle for øyeblikket. Jeg har derfor endret navn på den «gamle» `beta`-branchen til `beta_OLD` og opprettet en ny `beta`-branch med fungerende kode (basert på `master`).
Når det er på tide å merge inn arbeidet som ble påbegynt i fjor, kan man ta utgangspunkt i `beta_OLD`-branchen.

**Comment by SindreNordbo** [comment]
Etter en kjapp gjennomlesing av endringene i `beta_OLD` ser det ut som vi har fått hentet inn mesteparten til `master`/`beta`. Vurder å ta en grundig gjennomgang for å være helt sikker, men antagelig kan `beta_OLD` forkastes.
