### ISSUE TITLE
Ser ikke sammenheng mellomg TransportOkKvittering og Leveringskvittering

### ISSUE THREAD

**Issue by rogeraunet** [difi/sikker-digital-post-klient-dotnet#211]
Når jeg ser på TransportOkKvittering og LeveringsKvittering ser jeg ingen sammenheng mellom ID’ene. 
Hvordan kan jeg vite hvilket brev en LeveringsKvittering tilhører? 
 
I TEST:
Når jeg sender en brev via SikkerDigitalPostKlient får jeg følgende TranportOkKvittering
--
TransportOkKvittering:  
MeldingsId: 0d296eb3-24d7-4c3a-b598-ac9bb3cba76a 
ReferanseTilMeldingId: be87a96c-1c17-460b-b9a2-405003571b4e 
SendtTidspunkt: 01.10.2018 09:28:49
--
 
Etterpå leser jeg Kvitteringskøa og får følgende LeveringsKvittering
--
Leveringskvittering: 
MeldingsId: 42e11514-c93b-4f27-9771-eb96f763ca59 
ReferanseTilMeldingId: f15917f6-c1e9-40fe-bf44-a22d20c83ab8 
KonversasjonsId: f0053776-8420-4406-a206-490abd255307 
SendtTidspunkt: 10/1/2018 9:30:20 AM

**Comment by ArneHB** [comment]
@rogeraunet Du kan sette KonversasjonsId i det du oppretter Forsendelse objektet før du sender det til Difi. Dette blir den unike Iden som du kan bruke for å identifisere hvilken forsendelse/melding kvitteringen er knytt til. Det er ihvertfall det vi har gjort.
