### ISSUE TITLE
Manglende mapping av "Skyldig" i TransportFeiletKvittering

### ISSUE THREAD

**Issue by ArneHB** [difi/sikker-digital-post-klient-dotnet#219]
I Kvitteringsparser.cs:116 så ser det ut som man glemmer å mappe opp transportFeiletFelter.SkyldigFeiltype til TransportFeiletKvittering sin skyldig. Vi trenger å vite den skyldige parten i vår håndtering av TransportFeiletKvittering, om vi får Klientfeil så skal vi ikke prøve på nytt. Nå så defaulter den til Klient på skyldig. Har en av dere tid til å se på denne? Det haster litt å få en fiks på det

**Comment by AaronArrick** [comment]
TransportFeiletKvittering skal bare returneres om kvitteringsforespørselen er feilformatert, som anses som en klient feil. Skyldig feltet er derfor alltid satt til "Klient".

**Comment by ArneHB** [comment]
Takk for den oppklaringen @AaronArrick !

**Comment by ArneHB** [comment]
@AaronArrick Hvordan blir det håndtert feks om dere har problem med integrasjonen til posten (eller annen integrasjon). Vil man da få en _TransportOkKvittering_, så vil man få en _VarslingFeiletKvittering_ eller _Feilmelding_ når man henter kvitteringer?

**Comment by AaronArrick** [comment]
Du burde få en TransportOkKvittering selv om Digipost eller Eboks er nede. Om de er nede i mer enn en time vil man i så fall få en Feilmelding.
