### ISSUE TITLE
netstandard-target

### ISSUE THREAD

**Issue by AndreasLudviksen** [difi/sikker-digital-post-klient-dotnet#222]
We need to use this library from a library.
When do you plan to migrate it to netstandard ?

**Comment by johnksv** [comment]
Hi,
I'll look into it now.

**Comment by johnksv** [comment]
See #223 
Will merge and release as new major asap after review.
Please close this issue if that is sufficient.

**Comment by johnksv** [comment]
This is now avaliable on nuget. Version 4.0.0 targets .Net standard 2.0
https://www.nuget.org/packages/Difi.SikkerDigitalPost.Klient/
https://www.nuget.org/packages/Difi.SikkerDigitalPost.Klient.Domene/
https://www.nuget.org/packages/Difi.SikkerDigitalPost.Klient.Resources/

**Comment by AndreasLudviksen** [comment]
Wow! 
I'll give it a spin and let you know.
Thanks!

**Comment by AndreasLudviksen** [comment]
It seems the BouncyCastle-package is still on .NET Full.

Is it possible to move to the portable one, with support for .NETStandard2.0:
https://www.nuget.org/packages/Portable.BouncyCastle/1.8.6.7

**Comment by johnksv** [comment]
Ahh, yes. Thank you for noticing and pointing that out.
I will take a look at it when I get time. Hopefully later today or monday.
Also, you are welcome to submit a PR if you want to, @AndreasLudviksen . :)

**Comment by johnksv** [comment]
Hi,
Versjon 5.0.0 is now out, where BouncyCastle has been replaced with Portable.BouncyCastle.
https://www.nuget.org/packages/Difi.SikkerDigitalPost.Klient/5.0.0
