### ISSUE TITLE
Timeout håndtering av meldinger som har blitt sendt ok

### ISSUE THREAD

**Issue by ArneHB** [difi/sikker-digital-post-klient-dotnet#226]
Vi har den siste tiden fått en del timeouts ved sending av melding/forsendelse. Timeouten er satt til 45 sekunder. Meldingen/forsendelsen blir prosessert riktig, fordi neste gang vi prøver å sende den (siden vi har retry logikk rundt dette), så får vi TransportFeiletKvittering med beskrivelsen: "InstanceIdentifier or ConversationId already used.". Så meldingen med den KonversasjonsId gikk igjennom første gang selv om det timet ut og vi mottar også en "MottattKvittering" på denne meldingen når vi spør etter kvitteringer. 

Nå så flagger vi denne som feil, men egentlig så gikk meldingen igjennom. Så spørsmålet er hvilken data av den vi får i TransportFeiletKvittering kan vi bruke til å identifisere at meldingen allerede har gått igjennom?  Vi kan bruke "InstanceIdentifier or ConversationId already used.", men siden dette er en tekst som fort kan endre seg, så er ikke det en god løsning. Hadde det gått feks å fått en egen feilkode for denne situasjonen? #featurerequest

Dette er innholdet vi får i TransportFeiletKvitteringen nå:

    Alvorlighetsgrad: "failure"
    AntallBytesDokumentpakke: 145178
    Beskrivelse: "InstanceIdentifier or ConversationId already used."
    Feilkode: "EBMS:0003"
    Kategori: "Content"
    MeldingsId: "a421c2d2-ad3c-4472-986e-a068e6a99c6e"
    Opprinnelse: "ebMS"
    ReferanseTilMeldingId: null
    Rådata: "<env:Envelope xmlns:env=\"http://www.w3.org/2003/05/soap-envelope\">    <env:Header><eb:Messaging xmlns:eb=\"http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/\" env:mustUnderstand=\"true\"><ns6:SignalMessage xmlns:ns10=\"http://uri.etsi.org/2918/v1.2.1#\" xmlns:ns11=\"http://uri.etsi.org/01903/v1.3.2#\" xmlns:ns2=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ns3=\"http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader\" xmlns:ns4=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:ns5=\"http://www.w3.org/2000/09/xmldsig#\" xmlns:ns6=\"http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/\" xmlns:ns7=\"http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0\" xmlns:ns8=\"http://www.w3.org/1999/xlink\" xmlns:ns9=\"http://begrep.difi.no/sdp/schema_v10\"><ns6:MessageInfo><ns6:Timestamp>2020-05-27T13:48:20.173+02:00</ns6:Timestamp><ns6:MessageId>a421c2d2-ad3c-4472-986e-a068e6a99c6e</ns6:MessageId><ns6:RefToMessageId>39c8d634-3011-4e48-bda0-295fab588010</ns6:RefToMessag
    eId></ns6:MessageInfo><ns6:Error category=\"Content\" errorCode=\"EBMS:0003\" origin=\"ebMS\" refToMessageInError=\"39c8d634-3011-4e48-bda0-295fab588010\" severity=\"failure\" shortDescription=\"ValueInconsistent\"><ns6:Description xml:lang=\"en\">InstanceIdentifier or ConversationId already used.</ns6:Description></ns6:Error></ns6:SignalMessage></eb:Messaging></env:Header><env:Body><env:Fault><env:Code><env:Value>env:Sender</env:Value></env:Code><env:Reason><env:Text xml:lang=\"en\">ValueInconsistent</env:Text></env:Reason></env:Fault></env:Body></env:Envelope>"
    SendtTidspunkt: {27.05.2020 13:48:20}
    Skyldig: Klient
    Xml: "Document"

Vi ønsker ikke å forlenge timeouten siden dette vil kreve en del omskriving i retry logikken hos oss som blir brukt flere andre plasser.

**Comment by johnksv** [comment]
Hei, feilkoden (`EBMS:0003`) kan benyttes for å identifisere at ID-en allerede er benyttet (/allerede sendt).
Hvilket miljø er dette?

**Comment by ArneHB** [comment]
Supert takk! Det er mot produksjonsmiljøet, det startet den 24.04 (rundt da posten byttet sertifikat så kanskje relatert til dette), men det ser ut til å ha stabilisert seg til normal responstid nå etter mandag.
