### ISSUE TITLE
Mulighet/dokumentasjon for hvordan AsicE pakken hentes ut

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-dotnet#46]
Det må være en mulighet for å hente ut AsicE pakken som genereres av Avsender før meldingen sendes.
Dette er praktisk i forbindelse med testing og validering av det Avsender faktisk sender fra seg.
Det kan også være nyttig i forbindelse med arkivering av utgående post.

**Comment by asjafjell** [comment]
Beklager sent svar. Dette er noe som vil komme, men akkurat nå har fysisk post blitt prioritert som mer viktig.

**Comment by asjafjell** [comment]
Dette er nå implementert, og gjøres ved å sette et flagg på Send-metdoen som gir ut .zip-filen for AsicE-pakken på standard loggsti satt i innstillinger.
