### ISSUE TITLE
Difi design på dokumentasjon

### ISSUE THREAD

**Issue by kjorlaug** [difi/sikker-digital-post-klient-dotnet#77]
Endre til difi-profil

**Comment by asjafjell** [comment]
Hei, @kjorlaug!

Det er gjort mye riktig her. Det viktigste er at det er i tråd med Difis profil. Dessverre er også mye blitt dårligere. 

**Feil**
* Mye av tekst får veldig stor font og ser veldig malplassert ut, slik som lister og block-quotes, og  code
* Fjernet bruk av variabler fra _config.yaml i stedet for å endre variabelverdi
* Høyremeny er ikke ekspanderende

Sistnevnte er den kritiske og denne har jeg ikke selv implementert. Den er avhengig av stylesheets, navn på klasser og noen eksterne biblioteker, og krever en ukjent arbeidsmengde for å få tilbake til slik det var. Dette mener jeg er kritisk funksjonalitet fordi det gjør siden mye mer navigasjonsvennlig. Jeg anbefaler å sjekke hovrdan menyen fungerte på siste commit før designendring eller se [her](http://digipost.github.io/digipost-api-client-dotnet/) hvordan menyen skal oppføre seg. 

Kan du fikse dette?

**Comment by asjafjell** [comment]
Flott med rask respons, @kjorlaug! 

Nå ser det mye bedre ut! Litt småtteri igjen med størrelse på listeelementer osv.

**Comment by asjafjell** [comment]
Lukker denne, da vi har kommet til enighet for lenge siden.
